/* Only an explicitly verified receiver may be enabled in submission-config.json.
   No opaque no-cors requests and no speculative retries against the legacy receiver. */
'use strict';
let syncConfig=null,syncInFlight=false,syncTimer=null,identityEditing=!activeIdentity;
const profileForm=document.getElementById('student-form');
function validIdentity(p){return p&&p.name.trim()&&p.cls.trim()&&/^\d{1,3}$/.test(p.sid);}
function paintIdentity(){for(const [field,key] of [['name','name'],['class','cls'],['number','sid']]){const e=document.getElementById('student-'+field);e.value=activeIdentity?.[key]||'';e.readOnly=!!activeIdentity&&!identityEditing;}
 document.getElementById('save-student').hidden=!!activeIdentity&&!identityEditing;document.getElementById('change-student').hidden=!activeIdentity||identityEditing;
 document.getElementById('student-hint').textContent=activeIdentity&&!identityEditing?'已记住你的资料。 / Your profile is saved on this browser.':'Fill in your name, class and index number once. Your answers stay with your profile.';paintSync();}
function hasAnswers(rowState){return Object.values(rowState.rows).some(r=>r.value||r.first);}
function markProgressDirty(){if(!state.sync)state.sync=fresh().sync;state.sync.revision++;clearTimeout(syncTimer);if(typeof paintSync==='function'&&typeof syncConfig!=='undefined'){paintSync();syncTimer=setTimeout(()=>sendProgress(false),3000);}}
function readStudentState(key){const result=fresh(),raw=localStorage.getItem(key);if(!raw)return result;const parsed=JSON.parse(raw);if(parsed.version!==1||!parsed.rows)throw Error('无法读取这位学生的本机记录，请保留页面并告诉老师。');for(const q of DATA.questions){const r=parsed.rows[q.id];if(r&&typeof r.value==='string')result.rows[q.id]={...makeRow(),...r};}if(parsed.sync&&typeof parsed.sync.sessionId==='string')result.sync={...result.sync,...parsed.sync};return result;}
function renderProfileState(){document.getElementById('practice-questions').replaceChildren();for(const q of DATA.questions)document.getElementById('practice-questions').append(card(q));for(const id of Object.keys(reviewDrafts))delete reviewDrafts[id];switchTab('practice');updateSummary();paintIdentity();}
profileForm.addEventListener('submit',event=>{event.preventDefault();if(!profileForm.reportValidity())return;const identity={name:document.getElementById('student-name').value.trim(),cls:document.getElementById('student-class').value.trim().toUpperCase(),sid:document.getElementById('student-number').value.trim()};if(!validIdentity(identity))return;
 try{save();const targetKey=keyFor(identity);let target=readStudentState(targetKey);if(!activeIdentity&&hasAnswers(state)&&!hasAnswers(target)&&confirm('本机已有未署名的作答。是否归入“'+identity.name+'”？\n选“取消”会保留原记录，并为这位学生打开空白练习。'))target=state;localStorage.setItem(PROFILEKEY,JSON.stringify(identity));clearTimeout(syncTimer);activeIdentity=identity;KEY=targetKey;state=target;identityEditing=false;storageBlocked=false;save();renderProfileState();if(state.sync.revision>state.sync.ackedRevision)syncTimer=setTimeout(()=>sendProgress(false),3000);}catch(error){document.getElementById('student-hint').textContent=error.message;document.getElementById('student-hint').classList.add('student-error');}
});
document.getElementById('change-student').addEventListener('click',()=>{save();clearTimeout(syncTimer);identityEditing=true;paintIdentity();document.getElementById('student-name').focus();});
function snapshot(){const questions=DATA.questions.map(q=>{const r=state.rows[q.id],m=r.mistake,review=m?.reviews?.at(-1)||null;return {id:q.id,first:r.first?{answer:r.first.answer,time:r.first.time}:null,current:r.value,checked:isCurrent(r)?{answer:r.checked.answer,time:r.checked.time}:null,attemptCount:r.attempts.length,mistake:m?{firstWrong:m.firstWrong,lastWrong:m.lastWrong,wrongCount:m.wrongCount,status:m.status,reviewCount:m.reviews.length,lastReview:review?{answer:review.answer,time:review.time}:null}:null};});
 return {action:'vocabProgress',protocol:'hwt-vocab-progress-v1',lessonId:'2hcl-xuanci-2025',lessonTitle:'选词填空（2025）',spreadsheetId:'1XWGz1BBY4K5AfVsmZSYnqxXvlie2j2wiVFV0ZRF0-VE',student:{...activeIdentity},sessionId:state.sync.sessionId,revision:state.sync.revision,submissionId:state.sync.sessionId+':'+state.sync.revision,updatedAt:new Date().toISOString(),questions};}
function readyToSync(){return syncConfig?.enabled===true&&syncConfig.protocol==='hwt-vocab-progress-v1'&&/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(syncConfig.endpoint||'')&&syncConfig.spreadsheetId==='1XWGz1BBY4K5AfVsmZSYnqxXvlie2j2wiVFV0ZRF0-VE';}
function paintSync(message,type=''){const e=document.getElementById('sync-status'),b=document.getElementById('sync-button');if(!e)return;e.className='sync-status '+type;
 b.disabled=!readyToSync()||!activeIdentity||identityEditing||syncInFlight;
 if(message){e.textContent=message;return;}if(!readyToSync()){e.textContent='已存本机；成绩连接待老师完成设置。';return;}if(!activeIdentity||identityEditing){e.textContent='请先保存姓名、班级和学号。';return;}if(!navigator.onLine){e.textContent='目前离线，答案已存本机；联网后会重试。';return;}if(syncInFlight){e.textContent='提交中，答案仍保存在本机…';return;}if(state.sync.ackedRevision>=state.sync.revision&&state.sync.ackedAt){e.textContent='已提交老师 · '+new Date(state.sync.ackedAt).toLocaleTimeString('zh-SG',{hour:'2-digit',minute:'2-digit'});e.classList.add('saved');return;}e.textContent='有新进度待提交；已存本机。';}
function persistSync(target,key){try{localStorage.setItem(key,JSON.stringify(target));return true;}catch{return false;}}
async function sendProgress(manual=false){clearTimeout(syncTimer);if(syncInFlight||!readyToSync()||!activeIdentity||identityEditing){paintSync();return;}if(!navigator.onLine){paintSync();return;}if(!hasAnswers(state)){if(manual)paintSync('先完成一道题，再提交进度。');return;}
 const target=state,key=KEY,sync=target.sync;if(!sync.pending&&sync.revision<=sync.ackedRevision){paintSync();return;}if(!sync.pending)sync.pending=snapshot();const payload=sync.pending;if(!persistSync(target,key)){paintSync('无法保存待提交记录，请保留页面后重试。','failed');return;}
 syncInFlight=true;paintSync();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);let succeeded=false;
 try{const response=await fetch(syncConfig.endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),signal:controller.signal,redirect:'follow'});const r=await response.json();if(!response.ok||r.ok!==true||r.saved!==true||r.protocol!==payload.protocol||r.submissionId!==payload.submissionId||r.spreadsheetId!==payload.spreadsheetId||r.lessonId!==payload.lessonId||r.revision!==payload.revision)throw Error('未收到匹配的写入确认');
 sync.ackedRevision=Math.max(sync.ackedRevision,payload.revision);sync.ackedAt=new Date().toISOString();sync.pending=null;succeeded=true;persistSync(target,key);
 }catch(error){if(state===target)paintSync('提交未确认，答案已存本机。请按“重试提交”。','failed');}
 finally{clearTimeout(timer);syncInFlight=false;const b=document.getElementById('sync-button');b.textContent=succeeded?'提交进度':'重试提交';b.disabled=!readyToSync()||!activeIdentity||identityEditing;if(succeeded||state!==target)paintSync();if(succeeded&&state.sync.revision>state.sync.ackedRevision)syncTimer=setTimeout(()=>sendProgress(false),500);}
}
document.getElementById('sync-button').addEventListener('click',()=>sendProgress(true));window.addEventListener('online',()=>{paintSync();sendProgress(false);});window.addEventListener('offline',()=>paintSync());
(async()=>{try{const r=await fetch('submission-config.json',{cache:'no-store'});if(r.ok)syncConfig=await r.json();}catch{}paintIdentity();if(readyToSync()&&activeIdentity&&!identityEditing)sendProgress(false);})();
paintIdentity();
