'use strict';
const VERSION='20261002-s1-all-1',KEY='hwt-s1-vocab-concise-v1';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let D,L,S={},memoryOnly=false;
try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');if(x&&typeof x==='object'&&!Array.isArray(x))S=x}catch{memoryOnly=true}
function mix(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{memoryOnly=true}const t=$('#storage');if(t)t.textContent=memoryOnly?'此设备无法保存进度；离开后可能需要重做。':'进度只存在这台设备，不会自动上传。'}
function record(l){
 if(!S[l.id]||!Array.isArray(S[l.id].orders)||S[l.id].orders.length!==l.words.length){
 const labels=mix([0,1,2]),counts=[0,0,0];l.words.forEach((_,i)=>counts[labels[i%3]]++);const corePos=mix([labels[0],labels[0],labels[1],labels[1],labels[2]]);corePos.forEach(p=>counts[p]--);const rest=mix(counts.flatMap((n,i)=>Array(n).fill(i)));let c=0,r=0;
 S[l.id]={answers:{},cloze:{},checked:false,bank:mix(l.core),orders:l.words.map(w=>{const p=w.core?corePos[c++]:rest[r++];let a=mix([1,2]);a.splice(p,0,0);return a})};save();}
 const st=S[l.id];
 if(st.clozeVersion!==VERSION){st.cloze={};st.checkedGroups={};st.group=0;st.banks=l.groups.map(g=>mix(g.map(i=>l.cloze[i].word)));st.clozeVersion=VERSION;save()}
 return st;
}
const wordId=w=>'w-'+L.words.indexOf(w);
function footer(){return `<p id="storage" class="foot"></p><p class="foot">学习情境为教学改编或新设；图示帮助理解，不是课文照片。<br>不计时、不排名。朗读使用设备提供的普通话声音。</p>`}
function home(){L=null;const u=+(new URLSearchParams(location.search).get('unit')||0);$('#app').innerHTML=`<small>中一 · 单元一至六 · 按课文学习</small><h1>词语学习单</h1><p class="instruction">选一课，开始练习。 <small>Choose a lesson.</small></p><nav class="bar">${[0,1,2,3,4,5,6].map(n=>`<a class="${u===n?'active':''}" href="?${n?'unit='+n+'&':''}v=${VERSION}">${n?'单元'+n:'全部'}</a>`).join('')}</nav><div class="lessons">${D.lessons.filter(l=>!u||l.unit===u).map(l=>`<a class="lesson" href="#${l.id}"><small>单元${l.unit} · 第${l.lesson}课</small><h2>《${esc(l.title)}》</h2><p>5 个重点词 · ${l.cloze.length} 题填空</p><small>共 ${l.words.length} 个词，其他词语可补练</small></a>`).join('')}</div><p class="foot"><a class="teacher-link" href="teacher.html">教师参考与词表说明</a></p>`;document.title='中一 · 课文词语学习单'}
function card(w,i){return `<article class="card anchor" id="w-${i}" data-index="${i}"><div class="wordhead"><h3>${esc(w.word)}</h3><button class="sound" data-say="${esc(w.word)}" aria-label="朗读${esc(w.word)}">听</button></div>${visual(w)}<div class="hint"><span class="hint-label">字义线索</span><br>${esc(w.note)}</div>${w.culture?`<details class="culture"><summary>字形为什么这样写？</summary><p>${esc(w.culture)}</p></details>`:''}<p class="scene"><small>学习情境</small>${esc(w.scene)}</p><p class="question">${esc(w.question)}</p><div class="choices" role="group" aria-label="${esc(w.word)}的词义选择">${record(L).orders[i].map((k,n)=>`<button class="option" data-choice="${k}"><span class="letter">${'ABC'[n]}</span><span>${esc(w.options[k])}</span></button>`).join('')}</div><p class="feedback" aria-live="polite"></p></article>`}
function lesson(l){L=l;const st=record(l);document.title=`《${l.title}》词语学习单`;$('#app').innerHTML=`<a href="?unit=${l.unit}&v=${VERSION}">← 单元${l.unit}课文目录</a><p class="muted">中一 · 单元${l.unit} · 第${l.lesson}课</p><h1>《${esc(l.title)}》</h1><nav class="bar"><a href="#${l.id}" id="toWords">① 词义练习</a><button id="toCloze">② 选词填空</button><button class="reset" id="reset">重做本课</button></nav><h2>① 看字义，选词义</h2><p class="instruction">读情境，点选答案。 <small>Read and choose.</small></p><p id="progress" class="status" aria-live="polite"></p><div class="cards">${l.words.map((w,i)=>w.core?card(w,i):'').join('')}</div><details class="more"><summary>其他词语 · ${l.words.length-l.core.length} 个（按需补练）</summary><div class="extras">${l.words.map((w,i)=>w.core?'':`<details class="extra" data-extra="${i}"><summary>${esc(w.word)} <small class="extra-status"></small></summary>${card(w,i)}</details>`).join('')}</div></details><section class="anchor" id="cloze"><h2>② 选词填空</h2><div class="practice" id="clozePractice"></div></section>${footer()}`;
 $('#toCloze').onclick=()=>$('#cloze').scrollIntoView({behavior:'smooth'});$('#toWords').onclick=e=>{e.preventDefault();$('h2').scrollIntoView({behavior:'smooth'})};
 document.querySelectorAll('.card[data-index]').forEach(el=>{let i=+el.dataset.index;el.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>answer(i,+b.dataset.choice));paint(i)});
 document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say,b));
 renderCloze();if(l.words.length===l.core.length)$('.more').hidden=true;
 $('#reset').onclick=()=>{delete S[l.id];save();lesson(l)};progress();save();
 // Old direct links (#lesson/word/step) still reach the right term without the old multi-step workflow.
 const n=Number(location.hash.split('/')[1]);if(Number.isInteger(n)&&n>=0&&n<l.words.length){const el=$('#w-'+n);if(!l.words[n].core){$('.more').open=true;el.closest('.extra').open=true}requestAnimationFrame(()=>el.scrollIntoView())}
}
function answer(i,k){const st=record(L),prev=st.answers[i];if(prev?.correct)return;const a=prev||{attempts:0,firstCorrect:k===0};a.attempts++;a.selected=k;a.correct=k===0;st.answers[i]=a;save();paint(i);progress()}
function paint(i){const el=$('#w-'+i),w=L.words[i],a=record(L).answers[i];if(!a)return;el.querySelectorAll('[data-choice]').forEach(b=>{const selected=+b.dataset.choice===a.selected;b.classList.toggle('chosen',selected&&!a.correct);b.classList.toggle('correct',selected&&a.correct);b.disabled=!!a.correct;b.setAttribute('aria-pressed',String(selected))});const f=el.querySelector('.feedback');f.className='feedback '+(a.correct?'good':'bad');f.innerHTML=(a.correct?'✓ ':'再想想：')+esc(w.explain)+(a.correct?`<small>${esc(w.en)}</small>`:'');const badge=el.closest('.extra')?.querySelector('.extra-status');if(badge)badge.textContent=a.correct?'✓ 已完成':'再试试'}
function progress(){const st=record(L);const n=L.words.filter((w,i)=>w.core&&st.answers[i]?.correct).length;$('#progress').textContent=`重点词已完成 ${n} / ${L.core.length}`}
function renderCloze(){
 const st=record(L),g=st.group||0,indices=L.groups[g],bank=st.banks[g];
 $('#clozePractice').innerHTML=`<p class="instruction">点空格，选词语。从本课全部词语中选择，每词用一次。</p><p>本课全部 ${L.cloze.length} 个词 · 全部一起选</p><div class="wordbank">${bank.map(w=>`<span>${esc(w)}</span>`).join('')}</div>${indices.map(i=>{const q=L.cloze[i],[a,b]=q.sentence.split('__');return `<div class="cloze-row" data-cloze="${i}">${i+1}. ${esc(a)}<select aria-label="第${i+1}题答案"><option value="">选择词语</option>${bank.map(w=>`<option value="${esc(w)}">${esc(w)}</option>`).join('')}</select>${esc(b)}<p class="feedback" aria-live="polite"></p></div>`}).join('')}<div class="bar"><button class="primary" id="check">检查答案</button><button id="retryCloze">重做填空</button>${g<L.groups.length-1?'<button id="nextGroup">下一组 →</button>':''}</div><p id="result" class="result" aria-live="polite"></p><p id="clozeProgress" class="status" aria-live="polite"></p>`;
 document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{st.group=+b.dataset.group;save();renderCloze()});
 document.querySelectorAll('[data-cloze]').forEach(el=>{const i=+el.dataset.cloze,s=el.querySelector('select');s.value=st.cloze[i]||'';s.onchange=()=>{st.cloze[i]=s.value;delete st.checkedGroups[g];document.querySelectorAll('[data-cloze] .feedback').forEach(p=>p.textContent='');$('#result').textContent='';clozeProgress();save()}});
 $('#check').onclick=()=>checkCloze(true);
 $('#retryCloze').onclick=()=>{indices.forEach(i=>delete st.cloze[i]);delete st.checkedGroups[g];save();renderCloze()};
 if($('#nextGroup'))$('#nextGroup').onclick=()=>{st.group=g+1;save();renderCloze()};
 if(st.checkedGroups[g])checkCloze(false);clozeProgress();
}
function clozeOK(i,st){const v=st.cloze[i],q=L.cloze[i];return !!v&&(q.accepted||[q.word]).includes(v)&&Object.values(st.cloze).filter(x=>x===v).length===1}
function clozeProgress(){const st=record(L);let n=0;L.groups.forEach((g,j)=>{if(st.checkedGroups[j])g.forEach(i=>{if(clozeOK(i,st))n++})});$('#clozeProgress').textContent=`已检查并答对 ${n} / ${L.cloze.length} 题`}
function checkCloze(write){const st=record(L),g=st.group||0,total=L.groups[g].length;let n=0;document.querySelectorAll('[data-cloze]').forEach(el=>{const i=+el.dataset.cloze,q=L.cloze[i],s=el.querySelector('select'),f=el.querySelector('.feedback');const ok=clozeOK(i,st);if(ok)n++;f.className='feedback '+(ok?'good':'bad');f.textContent=!s.value?'请先选择一个词语。':ok?'✓ 正确':Object.values(st.cloze).filter(v=>v===s.value).length>1?'这个词已选了不止一次；全课每词用一次。':'再想想：'+q.hint});$('#result').textContent=n===total?'✓ 全部答对了！':`答对 ${n} / ${total} 题，可以修改后再检查。`;if(write){st.checkedGroups[g]=true;save()}clozeProgress()}
function speak(t,b){if(!('speechSynthesis'in window)){b.textContent='此设备不支持';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='zh-CN';u.rate=.8;const voices=speechSynthesis.getVoices();const v=voices.find(v=>/zh[-_]CN/i.test(v.lang));if(v)u.voice=v;u.onerror=()=>{b.textContent='再听一次'};speechSynthesis.speak(u)}
function route(){window.speechSynthesis?.cancel();const id=location.hash.slice(1).split('/')[0];const l=D.lessons.find(l=>l.id===id);if(l)lesson(l);else home()}
fetch('concise-data.json?v='+VERSION).then(r=>{if(!r.ok)throw Error('load');return r.json()}).then(d=>{D=d;route();window.addEventListener('hashchange',route)}).catch(()=>{$('#app').innerHTML='<h1>学习单暂时未能打开</h1><p>请检查网络后再试。</p><button onclick="location.reload()">重新打开</button>'});
