from pathlib import Path
import json,hashlib,html
P=Path(__file__).resolve().parent; data=(P/'data.json').read_text(); css=(P/'style.css').read_text(); engine=(P/'engine.js').read_text(); D=json.loads(data)
fingerprint=hashlib.sha256((css+data+engine).encode()).hexdigest()
student=(P/'shell.html').read_text().replace('__CSS__',css).replace('__DATA__',data.replace('</','<\\/')).replace('__ENGINE__',engine).replace('__FINGERPRINT__',fingerprint[:20])
student_name='2024-2hcl-yilunwen-hezuo.html'; teacher_name='2024-2hcl-yilunwen-hezuo-teacher.html'
(P/student_name).write_text(student)
esc=html.escape
sources={}
for prefix,paras in [('p',D['paras']),('t',D['transfer'])]:
 for i,p in enumerate(paras):
  for j,text in enumerate(p):sources[f'{prefix}{i+1}s{j+1}']=(('原文' if prefix=='p' else '新材料')+f'第{i+1}段 · 句{j+1}',text)
parts=[]
for t in D['tasks']:
 q=esc(t['q']).replace('【','<span class="qkey">').replace('】','</span>')
 part=f'<section class="card" id="{t["id"]}"><div class="mode">{esc(t["mode"])}</div><h2>{esc(t["title"])}</h2><p class="qtitle">{q}</p><p class="en">{esc(t["en"])}</p>'
 part+=''.join(f'<p class="answer">{esc(z)}</p>' for z in t['model'])
 part+=''.join(f'<p class="analysis-block">{esc(z)}<span class="en">{esc(en)}</span></p>' for z,en in t['analysis'])
 part+='<h3>原文依据库（教师备查） / Evidence inventory</h3>'
 for id in t['sources']:
  label,text=sources[id];part+=f'<a class="source-link" href="#src-{id}">{label}</a> '
 if not t['sources']:part+='<p>开放题使用生活经验，不设原文证据数量要求。<span class="en">Use an everyday example; there is no extract-count requirement.</span></p>'
 part+=f'<div class="comparison"><strong>比较追问 / Compare</strong><p>{esc(t["compare"])}</p></div></section>'
 parts.append(part)
extra_css='''body{max-width:1080px;margin:auto;padding:24px}.teacher-head{background:white;padding:25px;border:1px solid var(--line);border-radius:15px;margin-bottom:18px}.teacher-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.teacher-grid>div{border:1px solid var(--line);padding:13px;border-radius:9px}table{border-collapse:collapse;width:100%;font-size:16px;margin:12px 0}th,td{border:1px solid var(--line);padding:10px;text-align:left;vertical-align:top}th{background:var(--pale)}@media(max-width:750px){body{padding:12px}.teacher-grid{grid-template-columns:1fr}}@media print{body{display:block!important;padding:0}body>.teacher-head{display:block!important}.card{padding:10px 0;border:0}button,.tools{display:none!important}.answer,.evidence-text{font-size:12pt}.card{break-inside:auto}h2,h3{break-after:avoid}}'''
teacher_css='''body{font:17px/1.7 SimSun,'Songti SC',STSong,serif;color:#19364f;background:#f3f6fa}h1,.qtitle,.answer,.evidence-text{font-family:STKaiti,KaiTi,'Kaiti SC',DFKai-SB,serif}h1{font-size:32px}h2{font-size:24px}h3{font-size:20px}.qtitle{font-size:22px}.en{display:block;font-size:15px;line-height:1.5;color:#52677a;margin:4px 0 10px}.qkey{color:#ad293b;font-weight:bold;text-decoration:underline;text-underline-offset:5px}.card{padding:23px;background:white;border:1px solid #d3dfeb;border-radius:12px;margin:16px 0}.answer,.evidence-text{font-size:21px;line-height:1.9;white-space:pre-wrap}.answer{padding:13px;border-left:3px solid #1c5fa7;background:#f5f9ff}.analysis-block{font-size:17px}.source{border-top:1px solid #d3dfeb;padding-top:12px;scroll-margin-top:12px}.source-link{display:inline-block;margin:6px;color:#1c5fa7}.small,.mode,.version,.build{font-size:14px;color:#52677a}.banner,.comparison{padding:13px;background:#fff5df;border-radius:9px}.tools{display:flex;flex-wrap:wrap;gap:10px;align-items:center}button{font:inherit;padding:10px 15px;border:1px solid #d3dfeb;background:white;color:#1c5fa7;border-radius:8px;cursor:pointer}a{color:#1c5fa7}:root{--line:#d3dfeb;--pale:#edf4fb}p{overflow-wrap:anywhere}@media print{body{background:white;color:black}a{color:black}.en{font-size:10pt}h2,h3{break-after:avoid}}'''
head=f'''<!doctype html><html lang="zh-SG"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>合作｜教师答案与教学审查 · R3</title><style>{teacher_css}{extra_css}</style></head><body>
<div class="teacher-head"><span class="version">HEZUO-20260914-R3 · 教师专用 / Teacher only</span><h1>《合作》教师答案与教学审查</h1><p>本页含参考答案，不给学生作为独立练习入口。<span class="en">This page contains answers. Keep it separate during independent practice.</span></p><div class="tools"><button onclick="window.print()">打印教师说明 / Print guide</button><a href="{student_name}?v=3">打开学生端</a><a href="/#2/reading/1">返回中二考前强化</a></div></div>
<section class="card"><h2>本轮审查与取舍 / Audit and redesign</h2>
<table><thead><tr><th>旧版问题</th><th>本轮处理</th></tr></thead><tbody>
<tr><td>找中心论点前已经展示中心论点；“定义→说明重要性→强调”标题透露答案次序。</td><td>先提交自己的证据与尝试，再开放示范；词义帮助不直接代答。<span class="en">Attempt first. Show the model afterwards; language help does not supply the answer.</span></td></tr>
<tr><td>现成段意卡与预设论证图容易变成搬运；每段概括后又重复写全文内容。</td><td>从完整原文自行取材，归组、删减、去重并解释联系；只保留一次全文关系任务。<span class="en">Select and organise source text, explain its relevance, and avoid repeated whole-text summaries.</span></td></tr>
<tr><td>“即使个人能力强”被列为顺序因果的一环；两个并列要求被串成先后结果。</td><td>保留原文措辞，区分让步、并列与必要条件；“才能”不改成“保证获胜”。<span class="en">Keep concession, joint requirements and necessary conditions distinct. Do not turn them into guaranteed results.</span></td></tr>
<tr><td>原代码有已移除元素的事件绑定；保存只留输入框，不保留首次尝试及操作过程。</td><td>重建事件与状态管理；保存证据原句、节录、首次答案、提示、看参考时间、订正与理由。<span class="en">Rebuild event handling and preserve full learning records, including first attempts.</span></td></tr>
<tr><td>“完成”按钮可直接勾满，容易被误读为掌握。</td><td>仅显示已提交、已看参考、已订正；不自动评意义、不显示掌握百分比。<span class="en">Report actions, not mastery or semantic scores.</span></td></tr>
</tbody></table></section>
<section class="card"><h2>教学顺序与课堂安排 / Teaching sequence</h2><p>先通读五段，再做R1–R5。R1先尝试后看教师示范；R2–R3师生共构；R4–R5减少提示。然后作答原题Q50–Q53，最后完成新材料T1。不要为了赶进度把完整论证图提前投屏。<span class="en">Read first, model after an attempt, practise together, fade support, then use the original questions and the new passage.</span></p><p>建议分两段使用：第一段约35分钟用于篇章关系；第二段约30分钟用于原题、迁移和订正。程度较弱的班可分两课时，不宣称所有学生能在25分钟内完成全套。<span class="en">Allow about 35 minutes for reading relationships and 30 minutes for questions, transfer and revision. A weaker class may need two lessons.</span></p><div class="teacher-grid"><div><strong>观察理解，不只观察点击</strong><p>看学生能否说明“哪段材料支持哪种判断”，并在新材料中重新完成，而不是只认出标签。<span class="en">Check the evidence-to-claim explanation and its use in the new text.</span></p></div><div><strong>词汇困难与推理困难分开</strong><p>允许查中英词义及听词语；帮助使用会记录。看过提示后答出与未用提示独立答出，不作同一种表现。<span class="en">Separate language support from independent reasoning in your review.</span></p></div></div></section>
<section class="card"><h2>全文依据与分析边界 / Text model</h2><p>依老师已确定的分析：第一段首句总起，三个身份是例子，末句“无论我们身处何地、身居何职，都离不开与别人的合作”是中心论点。第三、四段分别展开有效合作的要求。<span class="en">Keep the teacher-confirmed thesis in the last sentence of paragraph 1. Paragraphs 3 and 4 develop conditions for effective cooperation.</span></p><p>分论点与中心论点的联系应解释为：文章从合作不可缺少，进一步说明怎样合作才有效；事例也展示合作的价值。不要把“提出了一个条件”自动当成“已经逻辑证明每个人都必须合作”。<span class="en">Explain development of the argument; merely stating a condition is not a complete proof of a universal claim.</span></p><p>“心中想着集体”与“自我牺牲”有关联，但不是同一个意义点。足球情境没有交代具体球员分工，不补造行为作为证据。<span class="en">Team-mindedness and sacrifice are related but distinct. Do not invent individual player duties.</span></p></section>
<section class="card"><h2>原题与分值 / Original questions and marking</h2><p>原题仍是 Q50（3分）、Q51（4分）、Q52（3分）、Q53（4分），共14分。网页不把这些分值转换成自动正确率。<span class="en">The original total remains 14 marks. The page does not turn it into an automated accuracy score.</span></p><p class="banner">本对话没有提供《合作》这四题的正式评分表。下面沿用前轮课堂参考的意义点；尤其Q53的1＋1＋2是课堂量表，不是已经核实的官方分配。若取得正式评分表，应逐点再校准，不能用其他年份的题目替代。<span class="en">No official marking scheme for these four questions was supplied. These are provisional classroom allocations, not verified official rules.</span></p><table><tr><th>题号</th><th>保留的课堂参考</th></tr><tr><td>Q50 · 3</td><td>排比；相关完整引句；突出不同身份都需要合作这一具体作用。</td></tr><tr><td>Q51 · 4</td><td>统一目标；做好本职；想着集体；自我牺牲。按意义保留，不要求四个片段或四句话。</td></tr><tr><td>Q52 · 3</td><td>交响乐团；演奏完美和谐；打动听众、感受音乐之美。</td></tr><tr><td>Q53 · 4</td><td>沿用课堂参考：立场1、阐释1、贴题生活例子2；接受有理据的其他立场，不机械匹配示例文字。</td></tr></table></section>'''
foot=f'''<section class="card"><h2>如何核对学习记录 / Reviewing records</h2><p>检查首次答案、提交前使用的帮助、之前看过的示范，再看订正与理由。首次提交只检查是否实际作答，不依字数、关键词或片段数判定对错。第2段蓝红只用于句子作用辨认，不能推出整段已掌握。<span class="en">Review first attempts, prior support and revisions. Submission is a completeness check, not a semantic grade; coloured labels are only a limited structural diagnosis.</span></p><p>原文节录保留对应原句与位置。允许删减及移动，但原句不可被改写成学生新增的信息。首次答案不因修订而改变；原题已接受教学支持的情况也会记录。<span class="en">Extracts keep their source wording. First attempts stay unchanged, and earlier support remains visible.</span></p><p>学习记录只在学生设备保存，不自动上传或汇总。下载的HTML可直接阅读。旧版记录另存，不冒充首次答案。本次没有加入排名、倒计时或新成绩服务。<span class="en">Records stay on the device until exported. Legacy notes are separate. No ranking, timer or new scoring service is added.</span></p></section>
<section class="card"><h2>来源与边界 / Sources and limits</h2><p>内容依据：本对话的完整篇章、原题、老师的段落分析与既有课堂参考；《议论文阅读技巧-HCL》《理解问答策略》《修辞的作用-HCL-高年级》；上传的 O-level-paper2-reference.zip 中 SKILL.md、argumentative.md、core-workflow.md、question-types-and-marking.md、open-ended-and-summary.md 及 source-register.md。<span class="en">The content follows the supplied passage, questions, teacher decisions, reading notes and uploaded Paper 2 reference skill.</span></p><p>制作依据：本对话已确定的 $build-hcl-reading-workshop 要求与本次完整审查清单；参考《德士司机和渐冻症的我》v6“先尝试、再参考、保留订正”的方法。本次检索未取得独立《华文阅读教学审查规范》原文件全文，不声称读过该原件。<span class="en">The design uses the workshop requirements established in this conversation and the current review checklist. The separately named audit document was not retrieved in full.</span></p><p>{esc(D['sourcesNote'])}<span class="en">Wording and provenance notes are retained; classroom answers are not presented as official marks.</span></p><p>术语统一使用中心论点、分论点、论据、论证、PEEL；Direct info 是明示信息，信息处理是筛选整合，语境解释是解释文中含义，Inference 是基于证据作出的未明说推断。不是每题都要出现四种处理。<span class="en">Keep the four types of processing distinct, using only those needed by each question.</span></p><p class="build">HEZUO-20260914-R3 · 学生内容与程序标识 {fingerprint[:20]}</p></section></body></html>'''
bank='<section class="card"><h2>完整原文依据库 / Complete evidence inventory</h2><p>以下按原文次序保留全部句子，并非学生必须收集的数量。<span class="en">All source sentences are retained for checking, not as a required extract count.</span></p>'+''.join(f'<div class="source" id="src-{id}"><strong>{label}</strong><p class="evidence-text">{esc(text)}</p></div>' for id,(label,text) in sources.items())+'</section>'
teacher=head+''.join(parts)+bank+foot
(P/teacher_name).write_text(teacher)
manifest={'version':D['version'],'fingerprint':fingerprint,'files':{}}
for n in (student_name,teacher_name):
 b=(P/n).read_bytes();manifest['files'][n]={'size':len(b),'sha256':hashlib.sha256(b).hexdigest(),'git_blob_sha':hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()}
(P/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2));print(json.dumps(manifest,ensure_ascii=False,indent=2))
