'use strict';
const D=JSON.parse(document.getElementById('lessonData').textContent), KEY='hwt.reading.hezuo.r3';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const clone=x=>JSON.parse(JSON.stringify(x)), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark=s=>esc(s).replace(/【(.*?)】/g,'<span class="qkey">$1</span>');
const now=()=>new Date().toISOString(), uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const meaningful=s=>/[\p{L}\p{N}]/u.test(String(s||'').replace(/[\u200b-\u200f\ufeff]/g,''));
const date=s=>s?new Date(s).toLocaleString('zh-SG',{timeZone:'Asia/Singapore',hour12:false}):'—';
const sources={}; D.paras.forEach((p,i)=>p.forEach((text,j)=>sources[`p${i+1}s${j+1}`]={id:`p${i+1}s${j+1}`,text,para:i+1,label:`原文第${i+1}段 · 句${j+1}`}));
D.transfer.forEach((p,i)=>p.forEach((text,j)=>sources[`t${i+1}s${j+1}`]={id:`t${i+1}s${j+1}`,text,para:i+1,label:`新材料第${i+1}段 · 句${j+1}`}));
function freshTask(t){return {draft:{answers:Object.fromEntries(t.fields.map(f=>[f.key,''])),evidence:[],roles:{}},first:null,hints:[],referenceViews:[],modelOpen:false,editing:false,revisions:[],reason:'',compared:false,events:[]};}
function fresh(){return {schema:3,version:D.version,createdAt:now(),updatedAt:now(),writer:'',seq:0,stage:0,current:'R1',view:'all',collect:false,target:0,identity:{name:'',className:'',indexNo:'',groupName:''},tasks:Object.fromEntries(D.tasks.map(t=>[t.id,freshTask(t)]))};}
let state=fresh(), blocked=false, corrupt=null, legacy=null, selection=null, trimming=null, spokenWord='', noticeTimer;
const writer=uid();
function warn(text){$('#storageWarning').hidden=false;$('#storageWarning').textContent=text;}
function load(){try{let raw=localStorage.getItem(KEY);if(raw){let x=JSON.parse(raw);if(x.schema!==3||!x.tasks||!D.tasks.some(t=>t.id===x.current))throw Error('Unexpected record format');state=x;D.tasks.forEach(t=>{state.tasks[t.id]=Object.assign(freshTask(t),state.tasks[t.id]||{});const a=state.tasks[t.id];a.draft=Object.assign(freshTask(t).draft,a.draft||{});});state.identity=Object.assign(fresh().identity,state.identity||{});}legacy=localStorage.getItem('hcl_coop_reasoning_v5');}catch(e){blocked=true;try{corrupt=localStorage.getItem(KEY)}catch(_){}warn('未能读取本机记录。原数据未覆盖；请先下载当前记录或重置本练习。 / Local records could not be read. Existing data has not been overwritten.');}}
function save(){state.updatedAt=now();if(blocked){$('#saveStatus').textContent='本页暂不写入本机 · Export before closing';return false;}try{state.writer=writer;state.seq=(state.seq||0)+1;localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='已在本机保存 · Saved on this device';return true;}catch(e){blocked=true;warn('本机保存不可用。作答仍在本页，请下载学习记录，不要直接关闭。 / Storage is unavailable. Export your work before closing.');$('#saveStatus').textContent='未写入本机 · Not saved locally';return false;}}
function toast(text){clearTimeout(noticeTimer);$('#notice').hidden=false;$('#notice').textContent=text;noticeTimer=setTimeout(()=>$('#notice').hidden=true,4200);}
function current(){return D.tasks.find(t=>t.id===state.current);}
function work(){return state.tasks[state.current];}
function editable(a=work()){return !a.first||a.editing;}
function events(type,detail){work().events.push({at:now(),type,detail});}
function help(id,type='hint'){const a=work();a.hints.push({id,type,at:now(),phase:a.first?'after-first':'before-first'});save();}
function stageTasks(){return D.tasks.filter(t=>t.stage===state.stage);}
function snapshot(t){const a=state.tasks[t.id];return {at:now(),answers:clone(a.draft.answers),evidence:clone(a.draft.evidence),roles:clone(a.draft.roles),helpUsed:clone(a.hints),priorReferenceTasks:D.tasks.filter(x=>x.id!==t.id&&state.tasks[x.id].referenceViews.length).map(x=>x.id)};}
function core(s){return JSON.stringify({answers:s.answers,evidence:s.evidence,roles:s.roles});}
function status(a){if(!a.first)return '待提交 · Not submitted';const revised=a.revisions.filter(r=>r.changed).length;return (revised?`已订正 ${revised} 次 · Revised`:a.referenceViews.length?'已看参考 · Reference viewed':'首次已提交 · First attempt saved')+(a.editing?'；订正草稿中 · Editing':'');}
function lastSnapshot(a){return a.revisions.length?a.revisions[a.revisions.length-1]:a.first;}
function validate(t,a){for(const f of t.fields){if(f.required&&!meaningful(a.draft.answers[f.key]))return '请先写下自己的尝试；空白或标点不能解锁参考。 / Write your own attempt before viewing a reference.';}
 if(t.roles&&!Object.keys(D.roleKeys).every(k=>a.draft.roles[k]))return '请先在第2段各组句后作出判断。 / Label each sentence group first.';
 if(t.requireEvidence&&!a.draft.evidence.length)return '请先自行选择相关原文，再提交解释。这里不规定固定片段数。 / Select relevant text first; there is no fixed extract count.';
 return '';}
function showError(message){const f=$('#taskFeedback');if(f){f.hidden=false;f.className='feedback alert';f.textContent=message;f.scrollIntoView({block:'nearest'});}else toast(message);}
function submit(){const t=current(),a=work();if(a.first)return;const error=validate(t,a);if(error){showError(error);return;}a.first=snapshot(t);a.editing=false;events('first-submit',{});save();renderTask();renderPassage();toast('首次尝试已保存，尚未判分。 / First attempt saved, not graded.');}
function startRevision(){const a=work();if(!a.first||a.editing)return;a.draft={answers:clone(lastSnapshot(a).answers),evidence:clone(lastSnapshot(a).evidence),roles:clone(lastSnapshot(a).roles)};a.reason='';a.editing=true;events('revision-start',{});save();renderTask();renderPassage();}
function saveRevision(){const t=current(),a=work();if(!a.first||!a.editing)return;const error=validate(t,a);if(error){showError(error);return;}if(!meaningful(a.reason)){showError('请写明改了什么、为什么改；只点按钮不算订正。 / Explain what you changed and why.');return;}
 const r=snapshot(t);r.reason=a.reason.trim();r.changed=core(r)!==core(lastSnapshot(a));r.referenceSeen=!!a.referenceViews.length;a.revisions.push(r);a.editing=false;a.reason='';events('revision-save',{changed:r.changed});save();renderTask();renderPassage();toast(r.changed?'订正及理由已保存，首次答案未改动。 / Revision saved; first answer preserved.':'核对说明已保存；没有内容修改，不标为订正。 / Comparison saved; no answer change.');}
function cancelRevision(){const a=work();if(!a.editing)return;if(!confirm('放弃这次尚未保存的订正？ / Discard this unsaved revision?'))return;const x=lastSnapshot(a);a.draft={answers:clone(x.answers),evidence:clone(x.evidence),roles:clone(x.roles)};a.editing=false;a.reason='';save();renderTask();renderPassage();}
function showReference(){const a=work();if(!a.first){showError('请先提交自己的尝试。 / Submit an attempt first.');return;}a.modelOpen=!a.modelOpen;if(a.modelOpen){a.referenceViews.push(now());events('view-reference',{});}save();renderTask();renderPassage();}
function goTask(id){if(!D.tasks.some(t=>t.id===id))return;state.current=id;state.stage=current().stage;state.target=0;state.collect=false;selection=null;save();render();}
function goStage(n){if(n===3){state.stage=3;state.collect=false;save();render();return;}const t=D.tasks.find(t=>t.stage===n&&t.id===state.current)||D.tasks.find(t=>t.stage===n);goTask(t.id);}
function addEvidence(source,text,group=state.target){const t=current(),a=work();if(state.stage===3||!editable(a)||!t.groups.length){toast('请先进入可作答或订正的任务。 / Open an editable task first.');return;}const s=sources[source];if(!s||!s.text.includes(text)||(t.stage===2)!==source.startsWith('t')){toast('请从当前材料选择原文。 / Select text from the current passage.');return;}
 group=Math.max(0,Math.min(t.groups.length-1,Number(group)||0));if(a.draft.evidence.some(e=>e.source===source&&e.text===text&&e.group===group)){toast('这段原文已在本组，可删减或整理。 / This extract is already in the group.');return;}
 a.draft.evidence.push({id:uid(),source,quote:s.text,text,group,label:'',at:now()});events('evidence-add',{source,text,group});save();renderTask();renderPassage();toast('原文已加入草稿；是否相关仍需你判断。 / Added to notes; you still need to judge its relevance.');}
function changeEvidence(action,id,value){if(!editable())return;const list=work().draft.evidence, i=list.findIndex(e=>e.id===id);if(i<0)return;const e=list[i];if(action==='remove'){list.splice(i,1);}else if(action==='up'||action==='down'){const j=i+(action==='up'?-1:1);if(j>=0&&j<list.length)[list[i],list[j]]=[list[j],list[i]];}else if(action==='group'){e.group=Number(value);}else if(action==='label'){e.label=value;save();return;}events('evidence-'+action,{source:e.source,id});save();renderTask();renderPassage();}
function openTrim(id){const a=work();if(!editable(a))return;const e=a.draft.evidence.find(x=>x.id===id);if(!e)return;trimming={task:state.current,id,quote:e.quote};$('#trimOriginal').textContent=e.quote;$('#trimText').value=e.text;$('#trimStatus').textContent='';const fr=e.quote.match(/[^，；。！？]+[，；。！？]?/g)||[e.quote];$('#trimFragments').innerHTML=fr.map((s,i)=>`<button class="frag ${e.text.includes(s)?'':'off'}" data-frag="${i}" aria-pressed="${e.text.includes(s)}">${esc(s)}</button>`).join('');trimming.fragments=fr;$('#trimDialog').showModal();}
function subsequence(whole,part){let i=0;for(const c of whole){if(c===part[i])i++;}return i===part.length;}
function applyTrim(){if(!trimming||trimming.task!==state.current)return;const e=work().draft.evidence.find(x=>x.id===trimming.id),value=$('#trimText').value.trim();if(!e||!editable())return;if(!meaningful(value)||!subsequence(e.quote,value)){$('#trimStatus').textContent='只能删减原文，不能添加或调换字词。 / Keep original wording and order; only remove text.';return;}const before=e.text;e.text=value;events('evidence-trim',{source:e.source,before,after:value});save();$('#trimDialog').close();renderTask();renderPassage();}
function wordMarkup(text){const words=Object.keys(D.words).sort((a,b)=>b.length-a.length), re=new RegExp(words.map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'g');let out='',pos=0;for(const m of text.matchAll(re)){out+=esc(text.slice(pos,m.index))+`<button class="vocab" data-word="${esc(m[0])}" aria-label="${esc(m[0])}：词语帮助">${esc(m[0])}</button>`;pos=m.index+m[0].length;}return out+esc(text.slice(pos));}
function roleMarkup(id){const t=current(),a=work();if(t.id!=='R2'||state.stage!==0||!D.roleKeys[id])return '';const chosen=a.draft.roles[id],seen=!!a.referenceViews.length;let h='<span class="roles" role="group" aria-label="句子作用">';D.roleOptions.forEach(([z,en])=>{let c=chosen===z?' selected':'';if(seen&&chosen===z)c+=z===D.roleKeys[id]?' correct':' wrong';h+=`<button class="role${c}" data-role-source="${id}" data-role-value="${z}" aria-pressed="${chosen===z}" ${editable(a)?'':'disabled'}>${z}<br>${en}</button>`;});h+='</span>';if(seen&&chosen){const r=D.roleReasons[id];h+=`<span class="role-note">${chosen===D.roleKeys[id]?'结构辨认与参考相符。':'这项辨认需要订正。'}${esc(r[0])}<span class="en">${esc(r[1])}</span></span>`;}return h;}
function renderPassage(){const t=current(),a=work(),transfer=state.stage===2;$('#passageTitle').textContent=transfer?'新编材料 / New passage':'完整篇章 / Full passage';$('#passageView').hidden=transfer;$('#passageView').value=state.view||'all';$('#collectBar').hidden=state.stage===3||!t.groups.length;$('#collectMode').checked=state.collect;$('#collectMode').disabled=!editable(a);$('#collectTarget').textContent=t.groups.length?`${t.id} · ${t.groups[state.target]||t.groups[0]}`:'';
 $('#passage').classList.toggle('collecting',state.collect);const pp=transfer?D.transfer:D.paras,prefix=transfer?'t':'p';let h=transfer?'<p class="transfer-label">新编练习：校园情境，并非真实学校新闻或原考题。<span class="en">A newly written school scenario, not news or a past exam.</span></p>':'';
 pp.forEach((p,i)=>{if(!transfer&&state.view!=='all'&&!String(state.view).includes(String(i+1)))return;h+=`<div class="para" id="paragraph-${prefix}${i+1}"><span class="pnum">第${i+1}段 · Paragraph ${i+1}</span>`;p.forEach((s,j)=>{const id=`${prefix}${i+1}s${j+1}`,chosen=a.draft.evidence.some(e=>e.source===id);h+=`<span class="sentence${chosen?' chosen':''}" id="source-${id}" data-source="${id}" draggable="true" tabindex="0" aria-label="${esc(sources[id].label)}">${wordMarkup(s)}</span>${roleMarkup(id)}`;});h+='</div>';});$('#passage').innerHTML=h;}
function evidenceMarkup(t,a){if(!t.groups.length)return '';let h='<details class="hint"><summary>证据操作 / How to use evidence</summary><p>先选一组，再开启点选。也可拖入句子，或划选一句中的短片段。已选材料可以删减、删除、移动、加归类名称；数量不代表得分。<span class="en">Choose a group, then tap, drag, or select part of a sentence. Trim, remove, move or label extracts. Their number is not a score.</span></p></details>';
 t.groups.forEach((g,k)=>{const list=a.draft.evidence.filter(e=>e.group===k);h+=`<section class="evidence" data-drop-group="${k}"><h3>${esc(g)}</h3><button data-target-group="${k}" ${editable(a)?'':'disabled'}>${state.target===k?'选入此组 · Active group':'选入此组 · Select group'}</button>`;if(!list.length)h+='<p class="empty">尚未选取。 / No extract yet.</p>';
 list.forEach(e=>{h+=`<div class="ev" draggable="${editable(a)}" data-evidence-id="${e.id}"><div class="small">${esc(sources[e.source]?.label||'原文')}${e.text!==e.quote?' · 节录 / Trimmed':''}</div><div class="evidence-text">${esc(e.text)}</div><div class="actions"><button data-ev-action="trim" data-id="${e.id}" ${editable(a)?'':'disabled'}>删减 / Trim</button><button data-ev-action="up" data-id="${e.id}" ${editable(a)?'':'disabled'} aria-label="证据上移">↑</button><button data-ev-action="down" data-id="${e.id}" ${editable(a)?'':'disabled'} aria-label="证据下移">↓</button><button data-ev-action="remove" data-id="${e.id}" ${editable(a)?'':'disabled'}>删除 / Remove</button></div>`;
 if(t.groups.length>1)h+=`<select aria-label="移动证据到另一组" data-move-evidence="${e.id}" ${editable(a)?'':'disabled'}>${t.groups.map((x,n)=>`<option value="${n}" ${n===e.group?'selected':''}>${esc(x)}</option>`).join('')}</select>`;
 h+=`<label>归类名称（可选） / Optional label<input type="text" data-label-evidence="${e.id}" value="${esc(e.label)}" maxlength="80" ${editable(a)?'':'readonly'}></label></div>`;});h+='</section>';});return h;}
function modelMarkup(t,a){if(!a.first||!a.modelOpen)return '';let h='<section class="model"><h3>参考与比较 / Reference & comparison</h3><p class="small">参考不是自动批改。 / This is not an automatic grade.</p>';h+=t.model.map(p=>`<p class="answer">${esc(p)}</p>`).join('');h+=t.analysis.map(([z,en])=>`<p class="analysis-block">${esc(z)}<span class="en">${esc(en)}</span></p>`).join('');if(t.sources.length){h+='<details><summary>原文来源 / Source text</summary>';t.sources.forEach(id=>{const s=sources[id];h+=`<div class="source"><button data-jump-source="${id}">${esc(s.label)}</button><p class="evidence-text">${esc(s.text)}</p></div>`;});h+='</details>';}
 h+=`<div class="comparison"><p>${esc(t.compare)}<span class="en">Compare your first attempt with the reference. Identify the difference and explain any revision.</span></p><label><input type="checkbox" id="compared" ${a.compared?'checked':''}>我已对照，不等于已经掌握。 / Compared, not a mastery claim.</label></div></section>`;return h;}
function renderTask(){if(state.stage===3){renderReview();return;}const t=current(),a=work();const list=stageTasks();$('#taskNav').hidden=false;$('#taskSelect').innerHTML=list.map(x=>`<option value="${x.id}" ${x.id===t.id?'selected':''}>${esc(x.title)}</option>`).join('');$('#prevBtn').disabled=D.tasks[0].id===t.id;$('#nextBtn').disabled=D.tasks[D.tasks.length-1].id===t.id;
 let h=`<article class="card" data-task="${t.id}"><div class="mode">${esc(t.mode)}</div><h2>${esc(t.title)}</h2><div class="qtitle">${mark(t.q)}</div><p class="en">${esc(t.en)}</p><p class="status">${esc(status(a))} · 不自动判分 / Not automatically graded</p>`;
 if(t.id==='R2')h+='<p class="guidance">在左侧第2段的句子后选择标签；提交并看参考后才显示蓝／红反馈。<span class="en">Label the sentence groups in paragraph 2 on the left. Blue/red feedback appears only after submission and reference viewing.</span></p>';
 if(t.hints.length){t.hints.forEach(([z,en],i)=>{const uses=a.hints.filter(x=>x.id===`hint-${i+1}`).length;h+=`<details class="hint" data-hint="hint-${i+1}"><summary>方法提示 ${i+1} / Help${uses?` · 已用 ${uses} 次`:''}</summary><p>${esc(z)}<span class="en">${esc(en)}</span></p></details>`;});}
 h+=evidenceMarkup(t,a);t.fields.forEach(f=>h+=`<label class="field" for="field-${f.key}"><strong>${esc(f.zh)}</strong><span class="en">${esc(f.en)}</span></label><textarea id="field-${f.key}" data-field="${f.key}" rows="${f.rows}" ${editable(a)?'':'readonly'} placeholder="写下自己的想法 / Your own response">${esc(a.draft.answers[f.key])}</textarea>`);
 h+='<div id="taskFeedback" class="feedback" role="status" hidden></div>';
 if(!a.first)h+='<div class="actions"><button id="submitFirst" class="primary">提交首次尝试 / Submit first attempt</button></div>';
 else {h+='<div class="actions">';h+=`<button id="viewReference">${a.modelOpen?'收起参考 / Hide reference':'查看示范与参考 / View reference'}</button>`;if(!a.editing)h+='<button id="startRevision" class="primary">开始订正 / Revise</button>';h+='</div><p class="small">首次答案已保留。要修改，请进入订正。 / The first attempt is preserved; use Revise to make changes.</p>';}
 h+=modelMarkup(t,a);
 if(a.editing){h+=`<section class="feedback"><label class="field" for="revisionReason"><strong>改了什么，为什么？</strong><span class="en">What did you change, and why?</span></label><textarea id="revisionReason" rows="3">${esc(a.reason)}</textarea><div class="actions"><button id="saveRevision" class="primary">保存订正与理由 / Save revision</button><button id="cancelRevision">放弃本次修改 / Cancel</button></div></section>`;}
 if(a.first){h+='<details><summary>查看首次答案（只读） / Original attempt</summary>'+snapshotMarkup(t,a.first,false)+'</details>';}
 h+='</article>';$('#work').innerHTML=h;$$('details[data-hint]').forEach(el=>el.addEventListener('toggle',()=>{if(el.open)help(el.dataset.hint);}));}
function render(){document.querySelectorAll('nav [data-stage]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.stage)===state.stage)));['name','className','indexNo','groupName'].forEach(k=>$('#'+k).value=state.identity[k]||'');$('#identitySummary').textContent=state.identity.name?'· '+state.identity.name:'';renderTask();renderPassage();}
function snapshotMarkup(t,s,includeHelp=true){if(!s)return '';let h=`<p class="small">${esc(date(s.at))} · Singapore time</p>`;t.fields.forEach(f=>{h+=`<h3>${esc(f.zh)}</h3><p class="answer">${esc(s.answers?.[f.key]||'（未填写 / Not entered）')}</p>`;});if(t.roles){h+='<p>';Object.keys(D.roleKeys).forEach(id=>h+=`${esc(sources[id].label)}：${esc(s.roles?.[id]||'未选')}<br>`);h+='</p>';}
 if(s.evidence?.length){h+='<h3>证据草稿 / Evidence notes</h3>';s.evidence.forEach(e=>h+=`<div class="source"><div class="small">${esc(t.groups[e.group]||'')} · ${esc(sources[e.source]?.label||e.source)}${e.label?' · '+esc(e.label):''}</div><p class="evidence-text">${esc(e.text)}</p>${e.text!==e.quote?`<p class="small">原句 / Original wording</p><p class="evidence-text">${esc(e.quote)}</p>`:''}</div>`);}else if(t.groups.length)h+='<p class="small">未选取证据片段。 / No selected extract.</p>';
 if(includeHelp){h+=`<p class="small">提交时帮助使用 ${s.helpUsed?.length||0} 次；此前看过的其他任务参考：${esc((s.priorReferenceTasks||[]).join('、')||'无')}。<br>Help uses at submission: ${s.helpUsed?.length||0}. Previously viewed models: ${esc((s.priorReferenceTasks||[]).join(', ')||'none')}.</p>`;}return h;}
function renderReview(){$('#taskNav').hidden=true;const total=D.tasks.length,first=D.tasks.filter(t=>state.tasks[t.id].first).length,views=D.tasks.filter(t=>state.tasks[t.id].referenceViews.length).length,rev=D.tasks.filter(t=>state.tasks[t.id].revisions.some(x=>x.changed)).length;
 let h=`<section class="card records"><h2>学习记录 / Learning record</h2><p>首次已提交 ${first}/${total} · 已看参考 ${views} · 已订正 ${rev}<span class="en">These counts describe activity, not marks or mastery.</span></p><p>未看过的参考答案不会出现在下载或打印记录中。<span class="en">Export and print include a reference only after you have viewed it.</span></p>`;
 D.tasks.forEach(t=>{const a=state.tasks[t.id];h+=`<section class="record"><h3>${esc(t.title)}</h3><p class="status">${esc(status(a))}</p><button data-open-task="${t.id}">回到本题 / Open task</button>`;if(a.first){h+='<details><summary>首次尝试 / First attempt</summary>'+snapshotMarkup(t,a.first)+'</details>';a.revisions.forEach((r,i)=>h+=`<details><summary>${r.changed?'订正':'核对说明'} ${i+1} · ${esc(date(r.at))}</summary>${snapshotMarkup(t,r)}<p>理由 / Reason</p><p class="answer">${esc(r.reason)}</p></details>`);}if(a.hints.length)h+=`<p class="small">帮助使用 ${a.hints.length} 次：${esc(a.hints.map(x=>x.id).join('、'))}</p>`;h+='</section>';});
 if(legacy)h+='<p class="banner">检测到旧版记录，未覆盖、也未当作首次答案。下载时附在记录末尾。 / Legacy notes are kept separately, not treated as first attempts.</p>';h+='</section>';$('#work').innerHTML=h;}
function recordFragment(){const id=state.identity;let h=`<h1>《合作》学习记录</h1><p>${esc(D.version)} · 导出 ${esc(date(now()))}</p><p>姓名 ${esc(id.name||'未填')}　班级 ${esc(id.className||'未填')}　学号 ${esc(id.indexNo||'未填')}　组别 ${esc(id.groupName||'未填')}</p><p>仅记录学习过程，不是自动评分或掌握证明。<span class="en">A process record, not an automatic grade or proof of mastery.</span></p><h2>完整原文 / Original passage</h2>`;
 D.paras.forEach((p,i)=>h+=`<p class="passage">〔${i+1}〕${esc(p.join(''))}</p>`);
 D.tasks.forEach(t=>{const a=state.tasks[t.id];h+=`<section class="record"><h2>${esc(t.title)}</h2><p class="qtitle">${mark(t.q)}</p><p>${esc(status(a))}</p>`;if(t.stage===2){h+='<p>新编课堂情境 / Newly written practice</p>';D.transfer.forEach(p=>h+=`<p class="passage">${esc(p.join(''))}</p>`);}if(a.first){h+='<h3>首次尝试 / First attempt</h3>'+snapshotMarkup(t,a.first);}else{h+='<h3>尚未提交的草稿 / Unsubmitted draft</h3>'+snapshotMarkup(t,{...a.draft,at:state.updatedAt},false);}
 a.revisions.forEach((r,i)=>h+=`<h3>${r.changed?'订正':'核对说明'} ${i+1}</h3>${snapshotMarkup(t,r)}<p>修改理由 / Reason</p><p class="answer">${esc(r.reason)}</p>`);
 if(a.editing)h+='<h3>尚未保存的订正草稿 / Unsaved revision draft</h3>'+snapshotMarkup(t,{...a.draft,at:state.updatedAt},false)+`<p class="answer">${esc(a.reason)}</p>`;
 if(a.referenceViews.length){h+='<h3>已查看的参考 / Viewed reference</h3>'+t.model.map(x=>`<p class="answer">${esc(x)}</p>`).join('')+t.analysis.map(([z,en])=>`<p>${esc(z)}<span class="en">${esc(en)}</span></p>`).join('');}
 h+=`<p>参考查看时间 / Reference views：${esc(a.referenceViews.map(date).join('；')||'无 / None')}</p><p>对照勾选 / Comparison checked：${a.compared?'是 / Yes':'否 / No'}</p>`;
 if(a.hints.length)h+='<h3>帮助使用 / Help log</h3>'+a.hints.map(x=>`<p class="small">${esc(date(x.at))} · ${esc(x.id)} · ${x.phase==='before-first'?'首次提交前 / Before first submission':'首次提交后 / After first submission'}</p>`).join('');
 if(a.events.length)h+='<details><summary>操作记录 / Actions</summary>'+a.events.map(e=>`<p class="small">${esc(date(e.at))} · ${esc(e.type)} · ${esc(JSON.stringify(e.detail))}</p>`).join('')+'</details>';h+='</section>';});
 if(legacy){h+='<h2>旧版记录（来源不等于首次作答）/ Legacy notes</h2>';try{const x=JSON.parse(legacy);Object.entries(x.inputs||{}).forEach(([k,v])=>h+=`<h3>${esc(k)}</h3><p class="answer">${esc(v)}</p>`);}catch(_){h+='<p class="answer">'+esc(legacy)+'</p>';}}
 if(corrupt)h+='<h2>未能解析的原存储备份 / Unparsed storage backup</h2><p class="print-block">'+esc(corrupt)+'</p>';
 return h+`<p class="small">${esc(D.sourcesNote)}</p>`;}
function recordDocument(){return '<!doctype html><html lang="zh-SG"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>合作学习记录</title><style>'+document.querySelector('style').textContent+'body{padding:24px;max-width:1000px;margin:auto;background:white}.answer,.record p{overflow-wrap:anywhere}.record details{margin:12px 0}@media print{#recordBody{display:block!important}}</style><body><div id="recordBody">'+recordFragment()+'</div></body></html>';}
function downloadRecord(){const blob=new Blob([recordDocument()],{type:'text/html;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;const name=(state.identity.name||'未填姓名').replace(/[^\p{L}\p{N}_-]/gu,'_').slice(0,40);a.download='合作_学习记录_'+name+'_'+new Date().toISOString().slice(0,10)+'.html';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);toast('已请求下载可直接阅读的HTML记录。 / Readable HTML download requested.');}
function preparePrint(){$('#printRoot').innerHTML=recordFragment();}
function reset(){try{localStorage.removeItem(KEY);}catch(e){warn('未能清除存储，请检查浏览器设置。 / Could not clear storage.');return;}state=fresh();blocked=false;corrupt=null;selection=null;$('#storageWarning').hidden=true;$('#resetDialog').close();save();render();toast('本练习已重置；其他记录未清除。 / Only this worksheet was reset.');}
function showWord(word){if(!D.words[word])return;spokenWord=word;help('word:'+word,'language');$('#wordTitle').textContent=word;const [z,en]=D.words[word];$('#wordBody').innerHTML=`<p>${esc(z)}<span class="en">${esc(en)}</span></p>`;$('#speechStatus').textContent='';if($('#wordsDialog').open)$('#wordsDialog').close();$('#wordDialog').showModal();}
function speak(){if(!('speechSynthesis'in window)||!('SpeechSynthesisUtterance'in window)){$('#speechStatus').textContent='本浏览器无朗读功能，请用设备的朗读所选内容。 / Use your device’s Speak Selection.';return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(spokenWord);u.lang='zh-CN';u.rate=.85;const voices=speechSynthesis.getVoices();u.voice=voices.find(x=>/^zh[-_]CN/i.test(x.lang))||voices.find(x=>/^zh/i.test(x.lang))||null;u.onstart=()=>$('#speechStatus').textContent='正在朗读 / Speaking';u.onend=()=>$('#speechStatus').textContent='朗读结束 / Finished';u.onerror=()=>$('#speechStatus').textContent='朗读未能完成，请检查设备的中文语音。 / Check the device’s Chinese voice.';$('#speechStatus').textContent='已请求朗读；可用语音取决于设备。 / Speech requested; voice availability depends on the device.';speechSynthesis.speak(u);}
function captureSelection(){const s=window.getSelection();if(!s||s.isCollapsed)return;const node=n=>n?.nodeType===1?n:n?.parentElement;const a=node(s.anchorNode)?.closest('.sentence'),b=node(s.focusNode)?.closest('.sentence');if(a&&a===b){const text=s.toString().trim(),source=a.dataset.source;if(text&&sources[source]?.text.includes(text))selection={source,text};}}
function jumpSource(id){const s=sources[id];if(!s)return;state.view='all';save();renderPassage();const el=$('#source-'+id);if(el)el.scrollIntoView({block:'center',behavior:'smooth'});}
// Event delegation keeps source text and user responses separate from executable markup.
document.addEventListener('click',e=>{const word=e.target.closest('[data-word]');if(word){e.stopPropagation();showWord(word.dataset.word);return;}const role=e.target.closest('[data-role-source]');if(role){if(!editable())return;const value=role.dataset.roleValue;if(!D.roleOptions.some(x=>x[0]===value))return;work().draft.roles[role.dataset.roleSource]=value;events('role-select',{source:role.dataset.roleSource,value});save();renderPassage();return;}
 const source=e.target.closest('.sentence');if(source&&state.collect&&state.stage!==3){if(window.getSelection()?.toString().trim())return;addEvidence(source.dataset.source,sources[source.dataset.source].text);return;}
 const target=e.target.closest('[data-target-group]');if(target){state.target=Number(target.dataset.targetGroup);state.collect=true;save();renderTask();renderPassage();toast('现在点选左侧相关原文。 / Tap relevant text on the left.');return;}
 const ev=e.target.closest('[data-ev-action]');if(ev){ev.dataset.evAction==='trim'?openTrim(ev.dataset.id):changeEvidence(ev.dataset.evAction,ev.dataset.id);return;}
 const close=e.target.closest('[data-close]');if(close){$('#'+close.dataset.close).close();return;}
 const j=e.target.closest('[data-jump-source]');if(j){jumpSource(j.dataset.jumpSource);return;}
 const task=e.target.closest('[data-open-task]');if(task){goTask(task.dataset.openTask);return;}
 const frag=e.target.closest('[data-frag]');if(frag&&trimming){frag.classList.toggle('off');frag.setAttribute('aria-pressed',String(!frag.classList.contains('off')));$('#trimText').value=$$('#trimFragments .frag').filter(x=>!x.classList.contains('off')).map(x=>trimming.fragments[Number(x.dataset.frag)]).join('');return;}
 const id=e.target.closest('button')?.id;
 if(id==='submitFirst')submit();else if(id==='viewReference')showReference();else if(id==='startRevision')startRevision();else if(id==='saveRevision')saveRevision();else if(id==='cancelRevision')cancelRevision();
});
document.addEventListener('input',e=>{const x=e.target;if(x.dataset.field&&editable()){work().draft.answers[x.dataset.field]=x.value;save();}else if(x.id==='revisionReason'&&work().editing){work().reason=x.value;save();}else if(x.dataset.labelEvidence){changeEvidence('label',x.dataset.labelEvidence,x.value);}else if(['name','className','indexNo','groupName'].includes(x.id)){state.identity[x.id]=x.value;$('#identitySummary').textContent=state.identity.name?'· '+state.identity.name:'';save();}});
document.addEventListener('change',e=>{const x=e.target;if(x.dataset.moveEvidence){changeEvidence('group',x.dataset.moveEvidence,x.value);}else if(x.id==='compared'){work().compared=x.checked;save();}});
$('#collectMode').onchange=()=>{state.collect=$('#collectMode').checked;save();renderPassage();};$('#passageView').onchange=()=>{state.view=$('#passageView').value;save();renderPassage();};$('#taskSelect').onchange=()=>goTask($('#taskSelect').value);
$$('nav [data-stage]').forEach(b=>b.onclick=()=>goStage(Number(b.dataset.stage)));
$('#prevBtn').onclick=()=>{const i=D.tasks.findIndex(t=>t.id===state.current);if(i>0)goTask(D.tasks[i-1].id);};$('#nextBtn').onclick=()=>{const i=D.tasks.findIndex(t=>t.id===state.current);if(i<D.tasks.length-1)goTask(D.tasks[i+1].id);};
$('#selectionBtn').onpointerdown=captureSelection;document.addEventListener('selectionchange',captureSelection);$('#selectionBtn').onclick=()=>{if(!selection){toast('请先在同一句原文中划选短片段。 / Select part of one sentence first.');return;}addEvidence(selection.source,selection.text);selection=null;window.getSelection()?.removeAllRanges();};
$('#wordHelpBtn').onclick=()=>{$('#wordList').innerHTML=Object.keys(D.words).map(w=>`<button data-word="${esc(w)}" class="kai">${esc(w)}</button>`).join('');$('#wordsDialog').showModal();};$('#speakBtn').onclick=speak;$('#wordDialog').addEventListener('close',()=>{if('speechSynthesis'in window)speechSynthesis.cancel();});
$('#applyTrim').onclick=applyTrim;$('#restoreTrim').onclick=()=>{if(trimming){$('#trimText').value=trimming.quote;$$('#trimFragments .frag').forEach(x=>{x.classList.remove('off');x.setAttribute('aria-pressed','true');});}};
$('#exportBtn').onclick=downloadRecord;$('#printBtn').onclick=()=>{preparePrint();window.print();};window.addEventListener('beforeprint',preparePrint);$('#resetBtn').onclick=()=>$('#resetDialog').showModal();$('#confirmReset').onclick=reset;$('#exportReset').onclick=()=>{downloadRecord();if(confirm('请确认记录已保存，再清空本机作答。 / Confirm the download is saved before clearing your work.'))reset();};
$('#reader').addEventListener('keydown',e=>{const el=e.target.closest('.sentence');if(el&&e.target===el&&(e.key==='Enter'||e.key===' ')&&state.collect){e.preventDefault();addEvidence(el.dataset.source,sources[el.dataset.source].text);}});
document.addEventListener('dragstart',e=>{const card=e.target.closest('.ev');if(card&&editable()){e.dataTransfer.setData('application/x-hwt-hezuo',JSON.stringify({kind:'evidence',id:card.dataset.evidenceId,task:state.current}));e.dataTransfer.effectAllowed='move';return;}const src=e.target.closest('.sentence');if(src){e.dataTransfer.setData('application/x-hwt-hezuo',JSON.stringify({kind:'source',source:src.dataset.source,text:sources[src.dataset.source].text}));e.dataTransfer.setData('text/plain',sources[src.dataset.source].text);e.dataTransfer.effectAllowed='copy';}});
document.addEventListener('dragover',e=>{const z=e.target.closest('[data-drop-group]');if(z&&editable()){e.preventDefault();z.classList.add('dropover');}});document.addEventListener('dragleave',e=>e.target.closest('[data-drop-group]')?.classList.remove('dropover'));
document.addEventListener('drop',e=>{const z=e.target.closest('[data-drop-group]');if(!z||!editable())return;e.preventDefault();z.classList.remove('dropover');try{const x=JSON.parse(e.dataTransfer.getData('application/x-hwt-hezuo'));if(x.kind==='source')addEvidence(x.source,x.text,z.dataset.dropGroup);else if(x.kind==='evidence'&&x.task===state.current)changeEvidence('group',x.id,z.dataset.dropGroup);}catch(_){toast('请从本页原文或证据卡片拖入。 / Drag from this page’s passage or evidence notes.');}});
window.addEventListener('storage',e=>{if(e.key!==KEY||!e.newValue)return;try{const x=JSON.parse(e.newValue);if(x.writer&&x.writer!==writer){blocked=true;warn('另一标签页更新了记录。本页已暂停写入以免覆盖；请先下载本页记录，再刷新。 / Another tab changed this record. Export this tab’s work before reloading.');$('#saveStatus').textContent='暂停写入 · Saving paused';}}catch(_){}});
load();render();if(!blocked)$('#saveStatus').textContent='本机记录就绪 · Local record ready';
