'use strict';
const LESSONS=window.EMAIL_LESSONS||[];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STEPS=['先看地图','挖讯息','认题型','想要点','查要点 · 小编辑','写成段','查格式','范文追踪','换题试写'];
const KINDS=['报告生活','分享经验','建议类','劝慰类','话题讨论类'];
const TYPES={'报告生活':'My situation → details（我的情况→细节）','分享经验':'Experience → action → result（经历→做法→结果）','建议类':'Problem → action → why it helps（问题→行动→作用）','劝慰类':'Feeling → reason → support（感受→原因→支持）','话题讨论类':'Stand → reason → explanation（立场→理由→解释）'};
let lesson=null,stage=0,mode='learn',grade=1,state={},storageOK=true;
function getState(id){try{return JSON.parse(localStorage.getItem('hwt-email-v1:'+id)||'{}')}catch(e){storageOK=false;return {}}}
function save(){if(!lesson)return;try{localStorage.setItem('hwt-email-v1:'+lesson.id,JSON.stringify(state));$('#saveState').textContent=' 已保存 / Saved.'}catch(e){storageOK=false;$('#saveState').textContent=' 无法自动保存，请先下载作答。'}}
function shuffle(a,key){let seed=[...key].reduce((s,c)=>(s*31+c.charCodeAt(0))>>>0,17);let b=[...a];for(let i=b.length-1;i>0;i--){seed=(seed*1664525+1013904223)>>>0;let j=seed%(i+1);[b[i],b[j]]=[b[j],b[i]]}return b}
function ta(key,label,placeholder='Write here（写在这里）',rows=3){return `<label for="${key}">${label}</label><textarea id="${key}" data-save="${key}" rows="${rows}" placeholder="${esc(placeholder)}">${esc(state[key]||'')}</textarea>`}
function check(key,label){return `<label class="check"><input type="checkbox" data-save="${key}" ${state[key]?'checked':''}><span>${label}</span></label>`}
function ref(key,body,label='参考思路 / See one example'){return `<button data-ref="${key}" aria-expanded="${!!state['ref-'+key]}">${label}</button><div class="reference ${state['ref-'+key]?'':'hidden'}" id="ref-${key}">${body}</div>`}
function quiz(key,prompt,options,correct,why){let order=shuffle(options,lesson.id+key),ans=state['quiz-'+key];return `<div class="taskbox"><p>${prompt}</p><div class="options">${order.map(o=>`<button data-quiz="${key}" data-value="${esc(o)}" class="${ans===o?(o===correct?'correct':'selected'):''}" aria-pressed="${ans===o}">${esc(o)}</button>`).join('')}</div><div class="feedback ${ans===correct?'good':''}" id="feedback-${key}" role="status">${ans===undefined?'':`${ans===correct?'✓ 判断正确':'再想一想 / Try again'}：${esc(why)}`}</div></div>`}
const quizMeta={};
function qz(key,prompt,options,correct,why){quizMeta[key]={correct,why};return quiz(key,prompt,options,correct,why)}
function go(id,s=0,m=mode){location.hash=`${id}/${s}/${m}`}
function catalogue(){lesson=null;const params=new URLSearchParams(location.search);grade=Number(params.get('grade'))===2?2:grade;$('#main').innerHTML=`<section class="hero"><div><div class="eyebrow">HUA WEN TONG · EMAIL STUDIO</div><h1>读懂来信，<br>写出有用的回应。</h1><p>先学会想，再练习写。<br>Read → Plan → Repair → Write</p><div class="actions"><a href="#intro" style="color:white">第一次学？从入门课开始 →</a></div></div><div class="mapbox"><h2 class="step">写作路线 / Your route</h2><div class="mapline">${['挖讯息','认题型','想要点','查要点','写成段','查格式'].map((s,i)=>`<span class="chip step">${i+1} ${s}</span>`).join('')}</div><p class="hint">每次改好一个问题。<br>Fix one thing well.</p></div></section><div class="tabs" aria-label="年级"><button data-grade="1" class="${grade===1?'active':''}">中一 · Start here</button><button data-grade="2" class="${grade===2?'active':''}">中二 · Think deeper</button></div><p class="hint">${grade===1?'从报告生活开始，再学建议、看法和多问任务。':'重点练立场、理由、可行办法和多方责任。'} 老师可直接分享每题链接。</p><div class="cards">${LESSONS.filter(l=>l.grade===grade).map((l,i)=>{const st=getState(l.id);const done=Object.keys(st).filter(k=>k.startsWith('done-')&&st[k]).length;return `<article class="card"><div class="number">${String(i+1).padStart(2,'0')} / SECONDARY ${l.grade}</div><h2>${esc(l.title)}</h2><span class="tag">${esc(l.level)}</span><p>${esc(l.questions.length)}个问题 · ${esc(l.objective)}</p><div class="status">${done?`已练 ${done} 个步骤 · 不代表已掌握`:'尚未开始'}</div><div class="actions"><button class="primary" data-open="${l.id}">开始学习</button><button data-editor="${l.id}">小编辑</button></div></article>`}).join('')}</div>`;bindHome()}
function bindHome(){document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{grade=+b.dataset.grade;history.replaceState(null,'',`?grade=${grade}`);catalogue()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>go(b.dataset.open,0,'learn'));document.querySelectorAll('[data-editor]').forEach(b=>b.onclick=()=>go(b.dataset.editor,4,'editor'))}
function intro(){lesson=null;$('#main').innerHTML=`<div class="panel"><a href="#">← 课程首页</a><h1>第一次学电邮 / Start here</h1><p>回邮要回应对方的情况与问题。每一步只做一件事。</p><div class="introgrid">${[['1 · 读懂来信','找出“我是谁、写给谁、他问什么”。Read the request.','school-life',1],['2 · 想清要点','要点答题，再解释情况、做法或理由。Plan and explain.','classmates',3],['3 · 换题独立写','先列提纲，再在纸上写完整电邮。Write independently.','friendship',3],['4 · 当小编辑','找问题、选修法，再改好自己的一句。Repair one sentence.','classmates',4]].map(x=>`<div class="taskbox"><h2 class="step">${x[0]}</h2><p>${x[1]}</p><button data-open="${x[2]}" data-s="${x[3]}">进入练习</button></div>`).join('')}</div><h2 class="step">一封回邮的结构</h2><p>主题 → 称呼 → 开头 → 回应感受（需要时）→ 逐问回答 → 结束语 → 祝词 → 署名</p><p class="hint">不是每题都需要安慰；看法写理由，建议写行动，报告生活写自己的情况。</p></div>`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>go(b.dataset.open,+b.dataset.s,'learn'))}
function render(){let parts=location.hash.slice(1).split('/');if(parts[0]==='intro'){intro();return}lesson=LESSONS.find(l=>l.id===parts[0]);if(!lesson){catalogue();return}stage=Math.max(0,Math.min(8,Number(parts[1])||0));mode=['learn','editor','independent'].includes(parts[2])?parts[2]:'learn';state=getState(lesson.id);Object.keys(quizMeta).forEach(k=>delete quizMeta[k]);document.title=`${lesson.title} · 电邮工作室`;$('#main').innerHTML=`<div class="lessonhead"><div><a href="?grade=${lesson.grade}">← 中${lesson.grade===1?'一':'二'}练习</a><h1>${esc(lesson.title)}</h1><span class="tag">${esc(lesson.level)}</span></div><div><label class="small" for="mode">练习方式 / Mode</label><select id="mode"><option value="learn" ${mode==='learn'?'selected':''}>完整学习 Learn</option><option value="editor" ${mode==='editor'?'selected':''}>10分钟小编辑 Repair</option><option value="independent" ${mode==='independent'?'selected':''}>独立练习 Write</option></select></div></div><nav class="navsteps" aria-label="学习步骤">${STEPS.map((s,i)=>`<button data-stage="${i}" class="${stage===i?'active':''}" aria-current="${stage===i?'step':'false'}">${i+1} ${s}${state['done-'+i]?' ✓':''}</button>`).join('')}</nav><div class="workspace"><aside class="letter"><h2>来信 / The email</h2><details open><summary>查看／收起来信 · Read email</summary><div class="letterinner"><div class="metadata">发件人：${esc(lesson.sender)}　→　收件人：${esc(lesson.writer)}<br>日期：${esc(lesson.date)}<br>主题：${esc(lesson.subject)}</div><p class="hint">Select / Copy / Paste · 可直接复制原文</p><div class="mailbody"><p>${esc(lesson.writer)}：</p>${lesson.mail.map((p,i)=>`<p id="mail-${i}">${esc(p)}</p>`).join('')}<p>${lesson.id==='dingcan'?'祝<br>学业进步':'祝好！'}<br>${esc(lesson.sender)}</p></div><div class="legend">${lesson.vocab.map(v=>`<span class="chip">${esc(v)}</span>`).join('')}</div><details><summary>资料说明 / Source</summary><p class="hint">${esc(lesson.source)}<br>${esc(lesson.sourceStatus)}<br>${esc(lesson.note)}</p></details></div></details></aside><section class="panel" id="task" aria-label="当前任务"><h2 class="step">${stage+1} ${STEPS[stage]}</h2>${content()}<div class="bottomnav"><button id="prev" ${stage===0?'disabled':''}>← 上一步</button><button class="primary" id="next">${stage===8?'回到课程':'下一步 →'}</button></div></section></div><div class="actions"><button id="download">下载本题作答</button><button id="reset">清空本题</button><span class="hint">练习记录仅在本浏览器，未发送给老师。</span></div>`;bind();highlightTask();}
function content(){const l=lesson;switch(stage){case 0:return `<p class="hint">${mode==='editor'?'约10分钟：先查要点，再修补一句，最后换题试写。':'先看一次，再自己做。Watch → Try → Write.'}</p><div class="mapline">${STEPS.slice(1,7).map((s,i)=>`<button class="step" data-stage="${i+1}">${s}</button>`).join('')}</div><div class="taskbox"><h3 class="step">本题要回答 / Your tasks</h3>${l.questions.map((q,i)=>`<p><b>Q${i+1}</b> ${esc(q.text)}</p>`).join('')}<p class="hint">${l.id==='school-life'?'原题要求200字以上。':'每问先准备两个有效要点；本题另有要求时按提示。'} 每个要点一段，不机械数行。</p></div><h3 class="step">先看一段 / See how it works</h3><div class="quote">${esc(l.questions[0].models[0])}</div><p class="hint">${esc(l.questions[0].guide)}</p><button data-evidence="${l.questions[0].evidence}">查看来信依据</button>${check('done-0','我知道本题要回答什么 / Ready to start')}`;
case 1:return `<p class="hint">找出身份和问题。Copy key words（复制关键词）。</p><div class="two">${ta('writer','我是谁？ / I am',l.writer,1)}${ta('recipient','写给谁？ / To whom',l.sender,1)}</div>${l.questions.map((q,i)=>ta('request-'+i,`Q${i+1} 对方问什么？ / Copy the request`)).join('')}${ref('requests',l.questions.map((q,i)=>`<p>Q${i+1}：${esc(q.text)}</p>`).join(''))}<h3 class="step">辨讯息 / What does this sentence do?</h3>${l.classification.map((c,i)=>qz('info'+i,esc(c.text),['寒暄','讯息','问题'],c.answer,c.why)).join('')}${check('done-1','我找齐问题了 / All requests found')}`;
case 2:return `<p class="hint">每问分别判断。Choose the job for each question.</p>${l.questions.map((q,i)=>qz('type'+i,`<b>Q${i+1}</b> ${esc(q.text)}`,KINDS,q.kind,`${q.kind}：${TYPES[q.kind]}。${q.guide}`)).join('')}<details><summary>五种任务，怎样回答？</summary>${Object.entries(TYPES).map(([k,v])=>`<p><b>${k}</b>：${v}</p>`).join('')}<p>混合类：同一封信有不同任务，逐问处理。</p></details><div class="reference"><b>回应感受 / Feelings</b><p>${esc(l.feeling)}</p></div>${check('done-2','我知道每问要写什么 / Task types checked')}`;
case 3:return `<p class="hint">${mode==='independent'?'先自己想，提示可按需要展开。Plan first; hints are optional.':'每问分别列要点。Do not mix the questions.'}</p>${l.questions.map((q,i)=>`<div class="taskbox"><h3 class="step">Q${i+1} ${esc(q.text)}</h3><p class="hint">${esc(q.guide)}</p>${ta('evidence-'+i,'用上哪项讯息？ / Copy useful context')}${q.kind==='话题讨论类'?ta('stand-'+i,'我的立场 / My stand','我认为……',2):''}${q.points.map((p,j)=>ta(`point-${i}-${j}`,`要点 ${j+1} / Point ${j+1}`,'先写一句，不抄整段。',2)).join('')}${ref('points'+i,`<ul>${q.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><p class="hint">这是一种思路，不是唯一答案。Other relevant points are welcome.</p>`)}</div>`).join('')}${check('plan-distinct','各要点不同，不重复 / Distinct points')}${check('done-3','已列要点，准备检查 / Plan ready')}`;
case 4:return `<p class="hint">教学改编片段，不是真实同学原句。先判断，再修补。<br>Spot → Choose → Repair</p><div class="tabs">${l.editors.map((e,i)=>`<button data-editor-index="${i}" class="${i===Number(state.editorIndex||0)?'active':''}">片段 ${i+1}</button>`).join('')}</div>${l.editors.map((e,i)=>i!==Number(state.editorIndex||0)?'':`<div class="taskbox"><h3 class="step">编辑任务 ${i+1}</h3><p><b>本段回答 Q${e.questionIndex+1}：</b>${esc(l.questions[e.questionIndex].text)}</p><p class="hint">${i===0?'留意题目事实与对象。':i===1?'检查是否答题、是否说清楚。':'这段也可能可以保留。'}</p><div class="quote">${esc(e.text)}</div>${qz('diagnose'+i,'这段怎样？ / Diagnose',['误读事实','答非所问','逻辑不通','不够清楚','可以保留'],e.label,e.why)}${qz('repair-choice'+i,'哪种修法更好？ / Choose a repair',[e.good,e.bad],e.good,e.need)}${ta('repair-'+i,'最少改一句 / Repair one sentence',e.need,2)}${check('paper-repair-'+i,'已在纸上修改 / Repaired on paper')}${ref('repair'+i,`<div class="kai">${esc(e.repair)}</div><p class="hint">${esc(e.need)} 自由作答未自动评分。</p>`)}</div>`).join('')}${check('done-4','已完成判断和修补 / Repair practice done')}`;
case 5:return `<p class="hint">只写一个重点段落。One point, one paragraph.</p><label for="targetQ">本段回答 / This paragraph answers</label><select id="targetQ" data-save="targetQ">${l.questions.map((q,i)=>`<option value="${i}" ${Number(state.targetQ||0)===i?'selected':''}>Q${i+1} ${esc(q.text)}</option>`).join('')}</select><div class="reference"><b class="step">衔接过渡 → 要点 → 解释</b><p class="hint">${esc(l.questions[Number(state.targetQ)||0].guide)}</p><details ${l.grade===1&&mode==='learn'?'open':''}><summary>提示 / Hints</summary><p>我回答哪一问？要点是什么？哪句话把要点说清楚？</p><p>What is my point? How does my explanation support it?</p><p>建议：怎样做、为什么有效。看法：理由、为什么支持立场。报告／经验：情况、做法、变化。</p></details></div>${ta('paragraph','我的段落 / My paragraph','首先，……',6)}${check('paper-paragraph','已在纸上写好 / Written on paper')}${check('paragraph-on-task','每句都在回答这一问 / Every sentence stays on task')}${check('paragraph-clear','有具体解释，不只是口号 / Explained clearly')}${ref('paragraph',`<div class="kai">${esc(l.questions[Number(state.targetQ)||0].models[0])}</div><p class="hint">参考一种写法。你的不同答案也可能成立。</p>`)}${check('done-5','段落已写好，等待核对 / Draft ready, not graded')}`;
case 6:return `<p class="hint">开头说准话题，结束语完整。Keep it short and clear.</p><div class="reference"><b class="step">开头：问候 → 话题 → 目的</b><p class="hint">Greeting → Topic → Purpose</p></div>${ta('opening','自己写开头 / Write the opening','不要只写“我来谈看法”，要说清谈什么。',3)}${ref('opening',`<div class="kai">${esc(l.opening)}</div>`)}<div class="reference"><b class="step">结束语 ≠ 祝词</b><p>结束语：收束＋希望／期待。<br>祝词：“祝好！”另写。署名：题目中的回信人。</p></div>${ta('closing','自己写结束语 / Write the closing','今天就写到这里。……',2)}${ref('closing',`<div class="kai">${esc(l.closing)}<br><br>祝好！<br><br>${esc(l.signature).replace(/\n/g,'<br>')}</div>`)}${qz('format','只有“祝好！”和署名，还缺什么？',['收束正文的结束语','重复前面的所有建议','介绍无关的新话题'],'收束正文的结束语','祝词不代替结束语。A wish is not a closing paragraph.')}${check('format-subject','主题用“回复：原主题” / Reply subject')}${check('format-name','称呼、署名符合身份 / Correct names')}${check('done-6','开头、结束语与格式已核对 / Checked')}`;
case 7:return model();
case 8:return `<p class="hint">换一个情境，不套原答案。Transfer to a new situation.</p><div class="quote">${esc(l.transfer.prompt)}</div>${ta('transfer','独立写两三句 / Write 2–3 sentences','先自己写，再看参考。',4)}${check('paper-transfer','已在纸上完成 / Written on paper')}${ref('transfer',`<div class="kai">${esc(l.transfer.sample)}</div><p class="hint">${esc(l.transfer.check)}</p>`)}<div class="taskbox"><h3 class="step">回到自己的电邮 / Your own email</h3><p class="hint">找一条要点，对照题目，改好一句。原段达标可保留。</p>${ta('own-before','我的原句 / Original sentence','也可直接在纸上修改。',2)}${ta('own-after','我的修改 / Revised sentence','只改必要的地方。',2)}${check('own-keep','原句达标，已标出题目依据 / Kept with evidence')}${check('own-paper','已在原作文上修改 / Repaired on paper')}</div>${check('done-8','已完成迁移与修订 / Practice completed')}<p class="notice">这是练习完成记录，不是自动作文评分。请由老师核对自由作答。</p>`;
}}
function model(){let l=lesson;return `<p class="hint">点击“对应来信”，看要点从哪里来。Tap to trace each paragraph.</p><p class="notice">教学示范，不是唯一答案。个人生活细节为拟写；写自己的经历时应保持合理、前后一致。</p><p class="role">主题：回复：${esc(l.subject)}</p><p class="kai">${esc(l.salutation)}</p><div class="modelpart"><span class="role">开头 · Greeting / Topic / Purpose</span><p class="modelbody">${esc(l.opening)}</p></div>${['classmates','friendship','classroom','team','energy','misinformation','recycling'].includes(l.id)?`<div class="modelpart"><span class="role">回应感受 · Respond</span><p class="modelbody">${esc(l.feeling)}</p></div>`:''}${l.questions.map((q,i)=>q.models.map((p,j)=>`<div class="modelpart"><span class="role">Q${i+1} · ${esc(q.kind)} · 要点${j+1}</span><p class="modelbody">${esc(p)}</p><button data-evidence="${q.evidence}">对应来信 / Trace</button><details><summary>这段怎样答题？ / Why it works</summary><p class="hint">${esc(q.points[j])}<br>${esc(q.guide)}</p></details></div>`).join('')).join('')}<div class="modelpart"><span class="role">结束语 · Closing</span><p class="modelbody">${esc(l.closing)}</p></div><p class="modelbody">祝好！<br><br>${esc(l.signature).replace(/\n/g,'<br>')}</p>${l.id==='recycling'?`<details><summary>本地回收知识 / Local guidance</summary><p class="hint">蓝色回收箱采用纸、塑料、玻璃、金属混合收集；物品是否适合投放须查指引。食物和液体不能一起投入。带押金标志的饮料容器可使用指定退还渠道。</p><a target="_blank" rel="noopener" href="https://www.nea.gov.sg/our-services/waste-management/3r-programmes-and-resources/national-recycling-programme">NEA：回收计划</a><br><a target="_blank" rel="noopener" href="https://www.nea.gov.sg/our-services/waste-management/beverage-container-return-scheme/for-consumers">NEA：饮料容器退还</a></details>`:''}${check('done-7','我能指出范文与题目的联系 / Connections checked')}`}
function highlightTask(){if([2,3,5].includes(stage))trace(lesson.questions[Number(state.targetQ)||0].evidence,false)}
function trace(index,scroll=true){document.querySelectorAll('.mailbody p').forEach(p=>p.classList.remove('evidence'));let el=$('#mail-'+index);if(el){$('.letter details').open=true;el.classList.add('evidence');if(scroll)el.scrollIntoView({behavior:'smooth',block:'nearest'})}}
function bind(){document.querySelectorAll('[data-editor-index]').forEach(b=>b.onclick=()=>{state.editorIndex=+b.dataset.editorIndex;save();render();$('#task').scrollIntoView({block:'start'})});document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>go(lesson.id,+b.dataset.stage));$('#mode').onchange=e=>go(lesson.id,e.target.value==='editor'?4:e.target.value==='independent'?3:0,e.target.value);document.querySelectorAll('[data-save]').forEach(el=>el.addEventListener(el.tagName==='TEXTAREA'?'input':'change',()=>{state[el.dataset.save]=el.type==='checkbox'?el.checked:el.value;save();if(el.id==='targetQ')render()}));document.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>{let k=b.dataset.quiz,m=quizMeta[k],v=b.dataset.value;state['quiz-'+k]=v;if(state['first-'+k]===undefined)state['first-'+k]=v===m.correct;save();let box=b.closest('.taskbox');box.querySelectorAll(`[data-quiz="${k}"]`).forEach(x=>{x.classList.remove('correct','selected');x.setAttribute('aria-pressed','false')});b.classList.add(v===m.correct?'correct':'selected');b.setAttribute('aria-pressed','true');let fb=$('#feedback-'+k);fb.className='feedback '+(v===m.correct?'good':'');fb.textContent=(v===m.correct?'✓ 判断正确：':'再想一想 / Try again：')+m.why});document.querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>{let k=b.dataset.ref;state['ref-'+k]=!state['ref-'+k];save();$('#ref-'+k).classList.toggle('hidden',!state['ref-'+k]);b.setAttribute('aria-expanded',String(!!state['ref-'+k]))});document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>trace(+b.dataset.evidence));$('#prev').onclick=()=>go(lesson.id,stage-1);$('#next').onclick=()=>stage===8?location.assign('?grade='+lesson.grade):go(lesson.id,mode==='editor'&&stage===4?8:stage+1);$('#download').onclick=downloadAnswers;$('#reset').onclick=()=>{if(confirm('只清空本题的作答与进度？Clear this lesson only?')){state={};save();render()}};if(!storageOK)$('#saveState').textContent=' 自动保存不可用，请下载作答。';}
function downloadFile(name,text,type='text/plain;charset=utf-8'){let u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function downloadAnswers(){let lines=[lesson.title+' · 学习记录','自由作答未自动评分。','时间：'+new Date().toLocaleString(),''];document.querySelectorAll('[data-save]');const labels={writer:'回信人',recipient:'收信人',opening:'开头',closing:'结束语',paragraph:'我的段落',transfer:'迁移短答','own-before':'原句','own-after':'修改句'};for(let[k,v]of Object.entries(state)){if(typeof v==='string'&&!k.startsWith('quiz-'))lines.push((labels[k]||k)+'：'+v);if(k.startsWith('paper-')&&v)lines.push(k+'：已在纸上完成')}const first=Object.keys(state).filter(k=>k.startsWith('first-'));lines.push('',`客观题首次判断正确：${first.filter(k=>state[k]).length}/${first.length}（仅已作答题）`,`已查看参考：${Object.keys(state).filter(k=>k.startsWith('ref-')&&state[k]).length}处`);downloadFile(lesson.id+'-作答.txt',lines.join('\n\n'))}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});render();
