'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lessons=window.EMAIL_LESSONS;let cards=[],photoURLs=[];
$('#lessonSelect').innerHTML=lessons.map(l=>`<option value="${l.id}">中${l.grade} · ${esc(l.title)}</option>`).join('');
$('#lessonTable').innerHTML='<table><tr><th>年级／题目</th><th>训练重点</th><th>来源与提醒</th></tr>'+lessons.map(l=>`<tr><td><a href="index.html?grade=${l.grade}#${l.id}/0/learn">中${l.grade} · ${esc(l.title)}</a></td><td>${esc(l.level)}<br>${l.questions.map(q=>esc(q.kind)).join('＋')}</td><td>${esc(l.source)}<br>${esc(l.note)}</td></tr>`).join('')+'</table>';
const current=()=>lessons.find(l=>l.id===$('#lessonSelect').value);
function status(s){$('#builderStatus').textContent=s}
function download(name,text,type){let u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('#guide').classList.toggle('hidden',b.dataset.view!=='guide');$('#builder').classList.toggle('hidden',b.dataset.view!=='builder')});
$('#photos').onchange=e=>{photoURLs.forEach(URL.revokeObjectURL);photoURLs=[];$('#photosPreview').replaceChildren();for(let f of [...e.target.files].slice(0,30)){if(!f.type.startsWith('image/'))continue;let u=URL.createObjectURL(f);photoURLs.push(u);let img=document.createElement('img');img.src=u;img.alt='教师本地作文照片预览';$('#photosPreview').append(img)}};
$('#lessonSelect').onchange=()=>{if(cards.length){cards=[];renderCards();status('题目已切换，请重新载入对应错例。')}$('#promptText').classList.add('hidden')};
$('#prompt').onclick=async()=>{let l=current();let text=`请根据附上的作文照片，整理电邮讲评候选错例。不要直接评分，不要杜撰学生原句。\n题目：${l.title}\n来信：${l.mail.join('\n')}\n作答任务：${l.questions.map((q,i)=>`Q${i+1} ${q.text}`).join('\n')}\n只选2—3个代表片段。优先审题、逻辑、展开。每例同时提供原句、照片页码及位置、对照题目的判断、最少修改建议。模糊文字标[不清楚]，禁止猜字。个人信息匿名；改编必须标明教学改编。考虑不同合理立场。由老师看原图确认后才能使用。\n仅返回JSON，结构为：{"lessonId":"${l.id}","cards":[{"questionIndex":0,"text":"匿名学生原句","label":"答非所问","why":"中文原因＋简短英文提示","good":"有效修改方向","bad":"看似合理但未解决问题的方向","repair":"最少修改参考句","need":"给学生的一项修改要求","source":"照片1，第2段；学生原句／有不清楚字／教学改编"}]}。questionIndex从0起，表示这段原本要回答哪一问。label只能为误读事实、答非所问、逻辑不通、不够清楚、可以保留。不要把未核实的文字错误当作学生错误。`;
$('#promptText').value=text;$('#promptText').classList.remove('hidden');try{await navigator.clipboard.writeText(text);status('指令已复制。请在你使用的AI中连同照片发送。')}catch(e){$('#promptText').select();status('请手动复制上面的指令。')}};
$('#loadSample').onclick=()=>{cards=current().editors.map(e=>({...e,source:'教学新编，非学生原句',approved:false}));renderCards();status('已载入3个教学错例，请核对。')};
function parse(raw){try{let d=JSON.parse(raw);if(d.lessonId!==current().id)throw Error('题目不一致，请切换到对应题目。');if(!Array.isArray(d.cards)||!d.cards.length||d.cards.length>12)throw Error('每次需要1—12个候选片段。');for(let c of d.cards){for(let k of ['text','label','why','good','bad','repair','need','source'])if(typeof c[k]!=='string'||!c[k].trim()||c[k].length>3000)throw Error('缺少有效字段：'+k);if(!['误读事实','答非所问','逻辑不通','不够清楚','可以保留'].includes(c.label))throw Error('诊断类别无效');if(!Number.isInteger(c.questionIndex)||!current().questions[c.questionIndex])throw Error('问题编号无效');if(c.good===c.bad)throw Error('两种修改方向不能相同')}cards=d.cards.map(c=>({...c,approved:false}));renderCards();status('已读取。请对照照片核对并勾选采用。')}catch(e){status('未导入：'+e.message)}}
$('#parse').onclick=()=>parse($('#jsonText').value);$('#jsonFile').onchange=async e=>{let f=e.target.files[0];if(f){if(f.size>1000000)return status('文件过大，请只导入错例JSON。');parse(await f.text())}};
function renderCards(){$('#reviewList').innerHTML=cards.map((c,i)=>`<article class="reviewcard"><h3 class="step">候选 ${i+1}</h3><label>对应问题<select data-i="${i}" data-key="questionIndex">${current().questions.map((q,j)=>`<option value="${j}" ${j===c.questionIndex?'selected':''}>Q${j+1} ${esc(q.text)}</option>`).join('')}</select></label>${[['text','匿名片段'],['why','诊断理由'],['good','有效修改方向'],['bad','干扰修改方向'],['repair','参考修改'],['need','学生任务'],['source','原图位置／来源']].map(([k,label])=>`<label>${label}<textarea data-i="${i}" data-key="${k}" rows="2">${esc(c[k])}</textarea></label>`).join('')}<label>诊断类别<select data-i="${i}" data-key="label">${['误读事实','答非所问','逻辑不通','不够清楚','可以保留'].map(s=>`<option ${c.label===s?'selected':''}>${s}</option>`).join('')}</select></label><label class="check"><input type="checkbox" data-i="${i}" data-key="approved" ${c.approved?'checked':''}>已核对原图／教学内容、任务位置及匿名信息，采用此例</label></article>`).join('');document.querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{let c=cards[+el.dataset.i],k=el.dataset.key;c[k]=k==='approved'?el.checked:k==='questionIndex'?+el.value:el.value;if(k!=='approved'){c.approved=false;document.querySelector(`[data-i="${el.dataset.i}"][data-key="approved"]`).checked=false}})}
function approved(){let out=cards.filter(c=>c.approved);if(!out.length){status('请先核对并勾选至少一个片段。');return null}return out}
$('#exportBank').onclick=()=>{let c=approved();if(c)download(current().id+'-错例.json',JSON.stringify({lessonId:current().id,cards:c},null,2),'application/json')};
$('#exportWorksheet').onclick=()=>{let c=approved();if(!c)return;let l=current();let payload=JSON.stringify({title:l.title,mail:l.mail,questions:l.questions.map(q=>q.text),cards:c.map(({source,approved,...x})=>x),transfer:l.transfer}).replace(/</g,'\\u003c');
let html=`<!doctype html><html lang="zh-Hans"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>电邮小编辑</title><style>body{max-width:850px;margin:auto;padding:24px;font:18px/1.8 system-ui;background:#f4f7fa;color:#16314f}h2,h3{color:#b5232b;font-weight:800}article,aside{background:white;padding:20px;border:1px solid #ccdbe7;border-radius:12px;margin:18px 0}button{padding:12px;margin:6px;border:1px solid #789;background:white;border-radius:8px;font:inherit;cursor:pointer}textarea{display:block;width:95%;min-height:90px;font:20px/1.8 KaiTi,serif}blockquote{font:22px/1.9 KaiTi,serif;margin:12px}.feedback{color:#8b2630}summary{cursor:pointer}button:focus-visible{outline:3px solid #cc9014}</style><h1 id="title"></h1><p>找错 → 选修法 → 改一句。自由作答由老师核对。</p><aside><details><summary>查看来信 / Read email</summary><div id="mail"></div></details></aside><main id="tasks"></main><script>const D=${payload};const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));document.getElementById('title').textContent=D.title+' · 小编辑';document.getElementById('mail').innerHTML=D.mail.map(p=>'<p>'+esc(p)+'</p>').join('');document.getElementById('tasks').innerHTML=D.cards.map((c,i)=>'<article><h2>'+ (i+1)+' 查要点</h2><p>本段回答：'+esc(D.questions[c.questionIndex])+'</p><blockquote>'+esc(c.text)+'</blockquote><div>'+['误读事实','答非所问','逻辑不通','不够清楚','可以保留'].map(s=>'<button data-i="'+i+'" data-kind="diagnose" data-val="'+esc(s)+'">'+s+'</button>').join('')+'</div><p id="f'+i+'" class="feedback" role="status"></p><h3>选修法</h3>'+ (i%2?[c.bad,c.good]:[c.good,c.bad]).map(s=>'<button data-i="'+i+'" data-kind="repair" data-val="'+esc(s)+'">'+esc(s)+'</button>').join('')+'<p id="r'+i+'" class="feedback" role="status"></p><h3>改一句</h3><label>'+esc(c.need)+'<textarea aria-label="修改句子"></textarea></label><details><summary>参考修改</summary><p>'+esc(c.repair)+'</p></details></article>').join('')+'<article><h2>换题试写</h2><p>'+esc(D.transfer.prompt)+'</p><textarea aria-label="迁移短答"></textarea><details><summary>参考</summary><p>'+esc(D.transfer.sample)+'</p><p>'+esc(D.transfer.check)+'</p></details></article>';document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{let c=D.cards[+b.dataset.i],diag=b.dataset.kind==='diagnose',ok=b.dataset.val===(diag?c.label:c.good);document.getElementById((diag?'f':'r')+b.dataset.i).textContent=(ok?'✓ 正确：':'再想一想：')+(diag?c.why:c.need)});<\/script></html>`;download(l.id+'-小编辑.html',html,'text/html;charset=utf-8');status('学习单已生成。照片与教师原图位置未包含在学生文件中。')};
