import test from 'node:test';import assert from 'node:assert/strict';
import {normalize,digest,CODE_RE} from '../supabase/functions/hwt-essay-admin/core.mjs';
import {freshCodes,csv,statusOf,remaining} from '../xie/zuowen-pigai/teacher-core.mjs';
const defaults={essays_total:8,new_essays_total:5,expiry:'2099-12-31',exam_level:'HCL',note:'测试',request_id:crypto.randomUUID()};
test('generated batches are unique and database payload contains only hashes',async()=>{const codes=freshCodes(100);assert.equal(new Set(codes).size,100);assert(codes.every(c=>CODE_RE.test(c)));const data=await normalize('create',{...defaults,codes});assert.equal(data.hashes.length,100);assert(!JSON.stringify(data).includes('HW-'));assert.equal(data.hashes[0],await digest(codes[0]));assert.equal(data.fingerprint,(await normalize('create',{...defaults,codes})).fingerprint);assert.notEqual(data.fingerprint,(await normalize('create',{...defaults,codes,note:'变更'})).fingerprint);});
test('invalid caps, dates, batches and stale credential types are rejected',async()=>{for(const bad of [{new_essays_total:9},{new_essays_total:0},{expiry:'2027-02-30'},{expiry:'2020-01-01'},{exam_level:'bad'},{essays_total:1.5},{codes:['HW-TEST-TEST','HW-TEST-TEST']},{codes:Array(101).fill('HW-TEST-TEST')}])await assert.rejects(normalize('create',{...defaults,codes:['HW-TEST-TEST'],...bad}));await assert.rejects(normalize('rotate',{id:1,revision:0,request_id:crypto.randomUUID(),code:'ADMIN'}));});
test('legacy shared quota and no-expiry edits remain supported',async()=>{const d=await normalize('update',{...defaults,id:1,revision:2,nickname:'测试',new_essays_total:0,expiry:''});assert.equal(d.new_essays_total,0);assert.equal(d.expiry,'');assert(!('essays_used' in d));});
test('code search hashes the exact code and cannot inject a REST filter',async()=>{const d=await normalize('list',{query:'hw-test-test'});assert.equal(d.query_hash,await digest('HW-TEST-TEST'));assert.equal(d.query,'');const q=await normalize('list',{query:'x),is_active.eq.1'});assert.equal(q.query,'x),is_active.eq.1');assert.equal(q.query_hash,'');});
test('CSV escapes quotes, newlines and spreadsheet formulas',()=>{const s=csv([['=1+1',' \t@SUM(1)','a"b','两\n行']]);assert(s.startsWith('\ufeff'));assert(s.includes('"\'=1+1"'));assert(s.includes('"\' \t@SUM(1)"'));assert(s.includes('"a""b"'));assert(s.includes('"两\n行"'));});
test('status uses inclusive Singapore expiry and both quota limits',()=>{const c={is_active:1,expiry:'2026-10-05',essays_total:8,essays_used:4,new_essays_total:5,new_essays_used:3};assert.equal(statusOf(c,'2026-10-05')[0],'可使用');assert.equal(statusOf(c,'2026-10-06')[0],'已过期');assert.equal(statusOf({...c,new_essays_used:5},'2026-10-05')[0],'额度已用完');assert.equal(statusOf({...c,is_active:0},'2026-10-06')[0],'已停用');assert.deepEqual(remaining(c),{total:4,fresh:2});assert.deepEqual(remaining({...c,new_essays_total:0}),{total:4,fresh:4});});
globalThis.Deno={env:{get:k=>({SUPABASE_URL:'https://db.invalid',SUPABASE_SERVICE_ROLE_KEY:'test-only'})[k]},serve:()=>{}};
const {handle}=await import('../supabase/functions/hwt-essay-admin/index.ts');
function request(action,headers={},body={}){return new Request('https://test.invalid',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({action,...body})});}
test('all actions reject unauthenticated callers and student codes before database access',async()=>{const original=globalThis.fetch;globalThis.fetch=()=>{throw Error('must not fetch');};try{for(const action of ['list','detail','create','update','set_active','rotate'])for(const headers of [{},{'x-hwt-session':'HW-TEST-TEST'}])assert.equal((await handle(request(action,headers,{code:'HW-TEST-TEST'}))).status,401);}finally{globalThis.fetch=original;}});
test('disallowed origin is rejected and CORS allows only the real app',async()=>{assert.equal((await handle(request('list',{origin:'https://evil.invalid'}))).status,403);const r=await handle(new Request('https://test.invalid',{method:'OPTIONS',headers:{origin:'https://huawentong-home.lyqlym2015.workers.dev'}}));assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://huawentong-home.lyqlym2015.workers.dev');});
test('expired or fabricated teacher sessions cannot read records',async()=>{const original=globalThis.fetch;let calls=[];globalThis.fetch=async url=>{calls.push(url);return Response.json([]);};try{assert.equal((await handle(request('list',{'x-hwt-session':'a'.repeat(64)}))).status,401);assert.equal(calls.length,1);assert(calls[0].includes('expires_at=gt.'));assert(!calls[0].includes('token_hash=eq.'+'a'.repeat(64)));}finally{globalThis.fetch=original;}});
test('valid teacher request sends hashed session and normalized data; transaction rechecks expiry',async()=>{const original=globalThis.fetch;let rpc;globalThis.fetch=async(url,opts)=>{if(url.includes('hwt_sessions?'))return Response.json([{expires_at:'2099'}]);if(url.includes('hwt_take_rate'))return Response.json(true);rpc=JSON.parse(opts.body);return Response.json({error:'教师登录已过期，请重新登录。',status:401});};try{const token='b'.repeat(64);const r=await handle(request('create',{'x-hwt-session':token},{...defaults,codes:['HW-TEST-TEST']}));assert.equal(r.status,401);assert.equal(rpc.p_session,await digest(token));assert(!JSON.stringify(rpc).includes('HW-TEST-TEST'));assert(!JSON.stringify(rpc).includes(token));}finally{globalThis.fetch=original;}});
test('database failure never exposes upstream details or credentials',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({code:'secret',message:'private student info'},{status:500});try{const r=await handle(request('list',{'x-hwt-session':'c'.repeat(64)}));assert.equal(r.status,503);assert(!JSON.stringify(await r.json()).includes('private'));}finally{globalThis.fetch=original;}});
