'use strict';
const VERSION='20261001-context-1',KEY='hwt-context-lab-v1';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let D,R={},timer,saveFailed=false,S={words:{},orders:{}};
try{let x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)S={...S,...x}}catch{}
let unit=Number(new URLSearchParams(location.search).get('unit')||0);
function save(){try{localStorage.setItem(KEY,JSON.stringify(S));saveFailed=false}catch{saveFailed=true}let x=$('#saveState');if(x){x.textContent=saveFailed?'本机存储已满或不可用，请导出记录。':'记录保存在本机；不会自动发送给老师。';x.className=saveFailed?'warn':'muted'}}
function entry(){const key=`${R.l.id}:${R.n}`;return S.words[key]||(S.words[key]={attempts:[],nodes:[],evidence:[],reflection:'',oral:false,glyph:{},question:'',lockUntil:0})}
function mix(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function order(l,i){if(!S.orders[l.id]){let positions=mix(l.words.map((_,n)=>n%3));S.orders[l.id]=positions.map(p=>{let wrong=mix([1,2]);wrong.splice(p,0,0);return wrong});save()}return S.orders[l.id][i]}
function route(){window.speechSynthesis?.cancel();clearTimeout(timer);let [id,n='0',step='observe']=location.hash.slice(1).split('/');let l=D.lessons.find(l=>l.id===id);R={l,n:Math.max(0,Math.min(Number(n)||0,l?l.words.length-1:0)),step:['observe','context','glyph'].includes(step)?step:'observe'};if(l)unit=l.unit;render()}
function go(l,n,step='observe'){const hash=`#${l.id}/${n}/${step}`;if(location.hash===hash)render();else location.hash=hash}
function status(a){if(!a)return'未开始';if(a.correct&&a.evidence?.length&&(a.reflection?.trim()||a.oral))return'已说依据';if(a.correct)return'已辨词义';if(a.attempts?.length)return'正在探究';return'已打开'}
function footer(){return `<p id="saveState" class="muted">${saveFailed?'本机存储已满或不可用，请导出记录。':'记录保存在本机；不会自动发送给老师。'}</p><p class="footer">课文初学 · 不计时、不排名 · ${VERSION}<br>示意图帮助理解关系；生活插图不是课文事件照片。学习记录不等于考试成绩。</p>`}
function home(){let ls=D.lessons.filter(l=>!unit||l.unit===unit);$('#app').innerHTML=`<span class="pill">中二 · 新课文词语学习</span><h1 class="cn">看明白，再说出为什么</h1><p>选一课，从老师指定的词语开始。</p><p class="action">看图找线索 → 回到课文说理由 → 观察字形</p><div class="bar"><label>单元 <select id="unit"><option value="0">全部</option>${[1,2,3,4].map(u=>`<option value="${u}" ${unit===u?'selected':''}>单元${u}</option>`).join('')}</select></label></div><div class="lessons">${ls.map(l=>`<a class="lesson" href="#${l.id}/0/observe"><span class="pill">单元${l.unit} · 第${l.lesson}课</span><h2 class="cn">《${esc(l.title)}》</h2><p>${l.words.length} 个词语 · ${l.words.filter((_,i)=>status(S.words[`${l.id}:${i}`])==='已说依据').length} 个已说依据</p><span class="muted">每次可选择一组约 5 个，也可自由选词。</span></a>`).join('')}</div>${footer()}`;$('#unit').onchange=e=>{unit=Number(e.target.value);home()}}
function marked(s,w){return esc(s).split(esc(w.target)).join(`<mark>${esc(w.target)}</mark>`)}
function quote(w,full=false){return `<div class="quote">${marked(full?w.fullSource:w.source,w)}</div>`}
function render(){if(!R.l)return home();const {l,n,step}=R,w=l.words[n],a=entry();let content=step==='observe'?observe(l,w,a):step==='context'?context(l,w,a):glyph(w,a);
$('#app').innerHTML=`<div class="bar"><button data-act="home">← 选课文</button><span class="pill">单元${l.unit} · 第${l.lesson}课</span><span class="spacer"></span><span class="muted">${n+1} / ${l.words.length}</span></div><h1 class="cn">《${esc(l.title)}》</h1><div class="bar"><h2 class="word">${esc(w.word)}</h2><button data-act="speak">听词语</button><span class="status">${status(a)}</span></div><div class="bar steps">${[['observe','① 观察辨义','Look & reason'],['context','② 回到课文','Find your evidence'],['glyph','③ 看清字形','Notice the parts']].map(([s,t,en])=>`<button class="${s===step?'active':''}" data-step="${s}">${t}<small>${en}</small></button>`).join('')}</div>${content}<div class="bar"><button data-act="prev" ${n===0?'disabled':''}>← 上一个词</button><button data-act="next" ${n===l.words.length-1?'disabled':''}>下一个词 →</button></div><details><summary>选择词语 / 查看本课进度</summary>${Array.from({length:Math.ceil(l.words.length/5)},(_,g)=>`<p class="group">第${g+1}组</p><div class="chips">${l.words.slice(g*5,g*5+5).map((x,j)=>`<button data-word="${g*5+j}" class="${g*5+j===n?'active':''}">${esc(x.word)} <small>${status(S.words[`${l.id}:${g*5+j}`])==='已说依据'?'✓':''}</small></button>`).join('')}</div>`).join('')}</details>${footer()}`;
bind();if(step==='observe')unlockTick();if(step==='glyph'&&$('#pad'))setupPad();}
function special(w){if(w.word==='亿'||w.word==='吨')return `<div class="special" aria-label="准确数量关系"><p class="meaning" style="text-align:center">${w.word==='亿'?'10 000 × 10 000 = 100 000 000<br><b>一万 × 一万 = 一亿</b>':'<b>1000 千克 = 1 吨</b>'}</p></div>`;
if(w.word==='锐减')return `<div class="special"><svg viewBox="0 0 480 145" role="img" aria-label="课文中鹿的数量，两年内从10万减到4万"><text x="5" y="29" font-size="18">原先</text><rect x="65" y="7" width="320" height="32" fill="#5c91ae"/><text x="395" y="30" font-size="18">10万</text><text x="5" y="101" font-size="18">两年后</text><rect x="65" y="78" width="128" height="32" fill="#bd655f"/><text x="205" y="101" font-size="18">4万</text></svg></div>`;
if(w.word==='趋势')return `<div class="special"><svg viewBox="0 0 480 140" role="img" aria-label="折线总体向下，中间有小幅回升；只作方向示意"><path d="M25 10v102h430" fill="none" stroke="#7b91a0" stroke-width="2"/><path d="M40 20 120 49 200 43 280 76 360 71 435 100" fill="none" stroke="#276c90" stroke-width="5"/><text x="100" y="135" font-size="16">方向示意，非课文数据：看总体，不只看一点</text></svg></div>`;
if(w.word==='褐')return `<div class="bar special" aria-label="颜色比较"><span style="background:#497dad;color:white;padding:20px">蓝</span><span style="background:#866447;color:white;padding:20px">褐</span><span style="background:#e1a9b8;color:#233b4c;padding:20px">粉红</span></div>`;return''}
function diagram(w,a){return special(w)+`<p class="action">点一点：哪一格最能帮你判断？</p><div class="visual">${w.nodes.map((node,i)=>`${i?'<span class="connector" aria-hidden="true">›</span>':''}<button class="node ${a.nodes.includes(i)?'selected':''}" data-node="${i}" aria-pressed="${a.nodes.includes(i)}">${pictogram(node.icon)}<b>${esc(node.label)}</b><small>${a.nodes.includes(i)?'已选作线索':'点此选线索'}</small></button>`).join('')}</div><p class="muted">关系示意 · 可选多格；选择线索不判分。</p>`}
function illustration(l,w){const rows=Math.ceil(l.words.length/3),x=w.index%3,y=Math.floor(w.index/3);return `<details><summary>再看一幅生活插图（辅助理解）</summary><div class="preview" role="img" aria-label="${esc(w.word)}的生活情境插图，不是课文事件照片" style="aspect-ratio:${l.artRatio};background-image:url('../visual-words/images/${l.id}.webp');background-size:300% ${rows*100}%;background-position:${x*50}% ${y/(rows-1)*100}%"></div><p class="note">生活情境可以不同；课文中的意思，以原句为准。</p></details>`}
function observe(l,w,a){const last=a.attempts.at(-1);return `<section class="card"><p class="action">先看图，再判断。<span class="gloss">Look for the key difference.</span></p>${diagram(w,a)}<details><summary>${esc(w.sourceLabel)} · 可边看图边读</summary>${quote(w)}</details><h3 class="question">${esc(w.question)}</h3><div class="options">${order(l,w.index).map((k,j)=>`<button data-answer="${k}" class="option ${a.correct&&k===0?'correct':!a.correct&&last?.choice===k?'wrong':''}" ${a.correct||a.lockUntil>Date.now()?'disabled':''}><span class="letter">${'ABC'[j]}</span><span>${esc(w.options[k])}</span></button>`).join('')}</div>${!a.correct&&last?`<div class="feedback" role="status"><b class="action">再观察一下</b><p>你选了“${esc(w.options[last.choice])}”。对照图中“${esc(w.nodes.at(-1).label)}”，再回到课文核对。</p><span id="lockMessage">先读提示，再试一次。</span>${a.attempts.length>=2?'<div class="bar"><button data-act="explain">看解释，再试</button></div>':''}</div>`:''}${a.peek&&!a.correct?`<div class="feedback"><p>${esc(w.explain)}</p><p class="muted">看懂后，再选择一次；这不作为独立检测。</p></div>`:''}${a.correct?`<div class="feedback good"><b class="action">抓住关键了</b><p>${esc(w.explain)}</p><p class="gloss">${esc(w.en)}</p><button class="primary" data-step="context">回课文找依据 →</button></div>`:''}${illustration(l,w)}</section>`}
function clauses(w){return w.source.split(/(?<=[，。！？；：])/).filter(x=>x.trim())}
function context(l,w,a){if(!a.correct)return `<section class="card"><p class="action">先观察、作一个判断，再回来说明依据。</p>${quote(w)}<button class="primary" data-step="observe">去观察辨义</button></section>`;const cs=clauses(w);return `<section class="card"><p class="action">${esc(w.sourceLabel)} · 《${esc(l.sourceTitle)}》</p><p class="muted">点选能帮助你理解的词句，可多选。Select evidence.</p><div class="evidence">${cs.map((s,i)=>`<button data-evidence="${i}" class="${a.evidence.includes(i)?'chosen':''}" aria-pressed="${a.evidence.includes(i)}">${marked(s,w)}</button>`).join('')}</div>${w.fullSource!==w.source?`<details><summary>展开完整语境</summary>${quote(w,true)}</details>`:''}${a.evidence.length?`<p class="evidence-note">我的依据：${esc(a.evidence.map(i=>cs[i]).join(''))}</p>`:''}<h3 class="action" style="margin-top:24px">说说为什么</h3><p>这里的“${esc(w.word)}”是指……<br>我从“……”看出来，因为……</p><textarea id="reflection" aria-label="我的语境解释" placeholder="可以写一句，也可以先和同桌说。">${esc(a.reflection)}</textarea><label><input type="checkbox" id="oral" ${a.oral?'checked':''}> 我已指着依据，向同桌或老师说明理由。</label><p class="muted">允许不同的合理依据。这一步不由电脑自动判对错。</p><div class="bar"><button data-act="compare" class="primary">对照理解</button><button data-step="glyph">观察字形 →</button></div>${a.compare?`<div class="feedback good"><p class="action">对照这两点，自行修订</p><p>${esc(w.explain)}</p><ul><li>我的解释有没有符合这句话中的对象、动作或感受？</li><li>我选的词句能不能支持解释，而不是只重复目标词？</li></ul></div>`:''}<p class="action">还有哪里不明白？</p><textarea id="question" aria-label="我还想问" placeholder="把疑问记下来，课堂上问老师。">${esc(a.question)}</textarea></section>`}
function glyph(w,a){const gi=Math.min(a.glyphIndex||0,Math.max(0,w.glyphs.length-1)),g=w.glyphs[gi];let body;if(g){const ga=a.glyph[g.char]||{};const opts=(w.index+gi)%2?[g.wrong,g.answer]:[g.answer,g.wrong];body=`<p class="action">放大看：“${esc(g.char)}”的${esc(g.focus)}是哪一个？</p><p class="muted">观察比较，不是默写测验。部件记忆不等于字源解释。</p><div class="glyphs">${w.glyphs.map((x,i)=>`<button data-glyph="${i}" class="${i===gi?'active':''}">${esc(x.char)}</button>`).join('')}</div><div class="char">${esc(g.char)}</div><p style="text-align:center">${esc(g.layout)}结构</p><div class="glyph-options">${opts.map(x=>`<button class="glyph-choice" data-part="${esc(x)}">${esc(x)}</button>`).join('')}</div>${ga.choice?`<div class="feedback ${ga.choice===g.answer?'good':''}"><b class="action">${ga.choice===g.answer?'看清楚了':'再对照完整的字形'}</b><p>${ga.choice===g.answer?esc(g.explain):`你选了“${esc(ga.choice)}”。比较它和“${esc(g.answer)}”的笔画，再看一遍上面的字。`}</p></div>`:''}`}
else body=`<p class="action">逐字看清楚，再读整个词。</p><p class="muted">这个词暂不作部件拆义；不能把每个部件都编成词源故事。</p><div class="glyphs">${[...w.word].map(ch=>`<button data-enlarge="${esc(ch)}">${esc(ch)}</button>`).join('')}</div><div class="char" id="largeChar">${esc(a.largeChar||w.word[0])}</div>`;
return `<section class="card">${body}<details id="writingDetails"><summary>想动笔：照着观察写一遍，再核对</summary><p class="word" id="writeModel">${esc(w.word)}</p><div class="bar"><button data-act="toggleModel">遮住／显示</button><button data-act="clearPad">重写</button></div><canvas id="pad" class="writing" aria-label="可用手指或笔练写词语"></canvas><p class="muted">也可以写在 workbook。电脑不判断字写得对不对；请对照部件和笔画。</p><p id="padStatus" class="muted"></p></details><div class="bar"><button data-step="context">← 回课文说理由</button><button data-act="next" ${R.n===R.l.words.length-1?'disabled':''}>下一个词 →</button></div></section>`}
function unlockTick(){if(R.step!=='observe')return;const a=entry();if(a.lockUntil>Date.now())timer=setTimeout(unlockTick,250);else{if(!a.correct)document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=false);if($('#lockMessage'))$('#lockMessage').textContent='现在可以再选择。'}}
function speak(){if(!window.speechSynthesis){alert('此浏览器暂不支持朗读。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(R.l.words[R.n].word);u.lang='zh-CN';u.rate=.8;speechSynthesis.speak(u)}
function bind(){document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>go(R.l,R.n,b.dataset.step));document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>go(R.l,Number(b.dataset.word)));document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{let a=entry(),i=Number(b.dataset.node);a.nodes=a.nodes.includes(i)?a.nodes.filter(x=>x!==i):[...a.nodes,i];save();render()});document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const a=entry();if(a.correct||a.lockUntil>Date.now())return;const k=Number(b.dataset.answer);a.attempts.push({choice:k,text:R.l.words[R.n].options[k],correct:k===0,afterExplanation:!!a.peek,time:new Date().toISOString()});if(k===0)a.correct=true;else a.lockUntil=Date.now()+5000;save();render()});document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{let a=entry(),i=Number(b.dataset.evidence);a.evidence=a.evidence.includes(i)?a.evidence.filter(x=>x!==i):[...a.evidence,i].sort((x,y)=>x-y);save();render()});if($('#reflection'))$('#reflection').oninput=e=>{entry().reflection=e.target.value;save()};if($('#question'))$('#question').oninput=e=>{entry().question=e.target.value;save()};if($('#oral'))$('#oral').onchange=e=>{entry().oral=e.target.checked;save()};document.querySelectorAll('[data-glyph]').forEach(b=>b.onclick=()=>{entry().glyphIndex=Number(b.dataset.glyph);save();render()});document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{let a=entry(),g=R.l.words[R.n].glyphs[a.glyphIndex||0];a.glyph[g.char]={choice:b.dataset.part,time:new Date().toISOString()};save();render()});document.querySelectorAll('[data-enlarge]').forEach(b=>b.onclick=()=>{entry().largeChar=b.dataset.enlarge;$('#largeChar').textContent=b.dataset.enlarge;save()});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act));}
function act(s){if(s==='home'){location.hash='';return}if(s==='speak'){speak();return}if(s==='prev'||s==='next'){let n=R.n+(s==='prev'?-1:1);if(n>=0&&n<R.l.words.length)go(R.l,n);return}const a=entry();if(s==='explain'){a.peek=true;save();render()}if(s==='compare'){if(!a.evidence.length){alert('先点选一句能帮助理解的课文。');return}if(!a.reflection.trim()&&!a.oral){alert('先写一句理由，或说给同桌听后勾选。');return}a.compare=true;save();render()}if(s==='toggleModel'){$('#writeModel').style.visibility=$('#writeModel').style.visibility==='hidden'?'visible':'hidden'}if(s==='clearPad'){try{localStorage.removeItem(KEY+':pad:'+R.l.id+':'+R.n)}catch{}setupPad()}}
function setupPad(clear=false){const c=$('#pad'),details=$('#writingDetails');if(!c||!details)return;const key=KEY+':pad:'+R.l.id+':'+R.n;const init=()=>{if(!details.open)return;let box=c.getBoundingClientRect();if(box.width===0)return;const ratio=window.devicePixelRatio||1;c.width=box.width*ratio;c.height=200*ratio;const ctx=c.getContext('2d');if(!ctx)return;ctx.scale(ratio,ratio);ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#203744';let old;try{old=clear?null:localStorage.getItem(key)}catch{}if(old){const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,box.width,200);im.src=old}let down=false;c.onpointerdown=e=>{down=true;c.setPointerCapture(e.pointerId);const b=c.getBoundingClientRect();ctx.beginPath();ctx.moveTo(e.clientX-b.left,e.clientY-b.top);e.preventDefault()};c.onpointermove=e=>{if(!down)return;const b=c.getBoundingClientRect();ctx.lineTo(e.clientX-b.left,e.clientY-b.top);ctx.stroke();e.preventDefault()};c.onpointerup=c.onpointercancel=()=>{if(!down)return;down=false;try{localStorage.setItem(key,c.toDataURL());$('#padStatus').textContent='练写已保存在本机。'}catch{$('#padStatus').textContent='练写图无法保存，请写在 workbook，或截图保留。'}}};details.ontoggle=()=>{if(details.open)init()};if(details.open)init();}
function download(data,type,name){let url=URL.createObjectURL(new Blob([data],{type}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function showRecords(){let ls=R.l?[R.l]:D.lessons.filter(l=>!unit||l.unit===unit);$('#dialogContent').innerHTML=`<h2>我的探究记录</h2><p class="muted">记录的是学习过程，不是考试正确率。口头说明为自己勾选，尚未经过老师评价。</p>${ls.map(l=>`<h3>《${esc(l.title)}》</h3><ul class="record-list">${l.words.map((w,i)=>{const a=S.words[`${l.id}:${i}`];return `<li><b>${esc(w.word)}</b> · ${status(a)}${a?.question?`<p>我的疑问：${esc(a.question)}</p>`:''}</li>`}).join('')}</ul>`).join('')}<div class="bar"><button id="export">导出文字记录</button><button id="backup">备份答题记录</button></div><p class="muted">下载后可交给老师。备份含选择、依据、解释与疑问；练写画布另存本机，不在此备份内。</p>`;$('#export').onclick=()=>{let out=[];for(const l of ls){out.push('《'+l.title+'》');l.words.forEach((w,i)=>{const a=S.words[`${l.id}:${i}`];if(!a)return;out.push(w.word+'：'+status(a),...(a.attempts||[]).map((x,j)=>`尝试${j+1}：${x.text}；${x.correct?'符合':'需再想'}${x.afterExplanation?'（看解释后）':''}`),'依据：'+(a.evidence||[]).map(n=>clauses(w)[n]).join(''),'我的解释：'+(a.reflection||''),'口头说明：'+(a.oral?'自己已勾选':'未勾选'),'疑问：'+(a.question||''),'')})}download(out.join('\n'),'text/plain;charset=utf-8','词语探究记录.txt')};$('#backup').onclick=()=>download(JSON.stringify(S,null,2),'application/json','词语探究备份.json');$('#dialog').showModal()}
$('#records').onclick=showRecords;$('#closeDialog').onclick=()=>$('#dialog').close();
fetch('data.json?v='+VERSION).then(r=>{if(!r.ok)throw Error('load');return r.json()}).then(d=>{D=d;$('#records').disabled=false;window.addEventListener('hashchange',route);route()}).catch(()=>{$('#app').innerHTML='<p>暂时无法加载。请刷新页面，或稍后再试。</p>'});
