'use strict';
const VERSION='20261001-1',KEY='hwt-visual-vocab-v1';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let D,S={profile:{name:'',class:'',number:''},answers:{},views:{},drawings:{},orders:{}},R={},saveError=false,timer;
try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)S={...S,...x}}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S));saveError=false}catch{saveError=true;}}
const params=new URLSearchParams(location.search);let grade=Number(params.get('grade')||1),unit=Number(params.get('unit')||0);
const words=()=>D.lessons.flatMap(l=>l.words.map((w,i)=>({...w,lid:l.id,wi:i})));
function art(l,i){const rows=Math.ceil(l.words.length/3),x=i%3,y=Math.floor(i/3);return `<div class="art" role="img" aria-label="${esc(l.words[i].scene)}" style="aspect-ratio:${l.artRatio||1.333};background-image:url('images/${l.id}.webp?v=${VERSION}');background-size:300% ${rows*100}%;background-position:${x*50}% ${rows===1?0:y/(rows-1)*100}%"></div><div class="art-note">Illustrated example（情境示意）</div>`}
function route(){window.speechSynthesis?.cancel();clearTimeout(timer);const [lid,mode='learn',n='0']=location.hash.slice(1).split('/');const l=D.lessons.find(x=>x.id===lid);R={l,mode:['learn','picture','use','write','review'].includes(mode)?mode:'learn',n:Math.max(0,Math.min(Number(n)||0,l?l.words.length-1:0))};render()}
function goto(l,m,n=0){location.hash=`${l.id}/${m}/${n}`}
function recordFor(l,i,m){const k=`${l.id}:${i}:${m}`;return S.answers[k]||(S.answers[k]={attempts:[],help:false,done:false,lockUntil:0})}
function score(l){let arr=l.words.map((_,i)=>S.answers[`${l.id}:${i}:use`]).filter(Boolean);return {done:arr.filter(a=>a.done).length,first:arr.filter(a=>a.attempts[0]?.ok&&!a.attempts[0]?.help).length}}
function render(){if(!R.l)return home();const {l,mode,n}=R,w=l.words[n],sc=score(l);let body='';
const head=`<div class="bar"><button data-act="home">← Lessons（课文）</button><span class="tag">中${l.grade===1?'一':'二'} · 单元${l.unit} · 第${l.lesson}课</span></div><h1 class="cn">《${esc(l.title)}》</h1><div class="bar tabs">${[['learn','Look（看图）'],['picture','Match（认词）'],['use','Use（运用）'],['write','Write（手写）'],['review','Review（复习）']].map(([m,t])=>`<button class="${m===mode?'active':''}" data-mode="${m}">${t}</button>`).join('')}</div>`;
if(mode==='review'){body=review(l)}else if(mode==='learn'){S.views[`${l.id}:${n}`]=true;save();body=`<div class="card split"><div>${art(l,n)}</div><div><div class="step">Look & understand（看图懂词）</div><h2 class="word">${esc(w.w)}</h2><p>${esc(w.en)}</p><p class="meaning cn">${esc(w.zh)}</p><p class="sentence">${esc(w.scene)}</p><button data-act="speak">Listen（听词语）</button>${w.note?`<details><summary>In context（语境）</summary><p>${esc(w.note)}</p></details>`:''}<div class="bar"><button class="primary" data-mode="picture">Try this word（试一试）→</button></div></div></div>`}else if(mode==='write'){body=writing(l,n,w)}else{body=quiz(l,n,w,mode)}
$('#app').innerHTML=head+`<div class="bar"><span>${mode==='review'?'':`${n+1} / ${l.words.length} words（词语）`}</span><span class="sub">Use: ${sc.done}/${l.words.length} completed · Independent first try: ${sc.first}/${l.words.length}</span></div>`+body+(mode==='review'?'':`<div class="bar"><button data-act="prev" ${n===0?'disabled':''}>← Previous（上一个）</button><button data-act="next" ${n===l.words.length-1?'disabled':''}>Next（下一个）→</button></div><details><summary>Word list（选词语）</summary><div class="chips">${l.words.map((x,i)=>`<button data-word="${i}" class="${i===n?'active':''}">${esc(x.w)}</button>`).join('')}</div></details>`)+foot();bind();if(mode==='write')initCanvas();if(mode==='picture'||mode==='use')lockTick();}
function foot(){return `<p class="footer">No timer · No leaderboard（不计时、不排名）<br>${saveError?'Saving unavailable — export your record（无法保存，请导出记录）':'Progress saved on this device（进度保存在本机）'} · ${VERSION}<br>Pictures and practice sentences are newly created learning examples（图示及练习句为新编）.</p>`}
function home(){const list=D.lessons.filter(l=>l.grade===grade&&(!unit||l.unit===unit));$('#app').innerHTML=`<h1>Look. Understand. Use.<br><span class="cn">看图懂词语</span></h1><p class="sub">Choose a lesson, then learn one word at a time（选课文，逐词学习）.</p><div class="bar"><button data-grade="1" class="${grade===1?'primary':''}">中一 · 单元三</button><button data-grade="2" class="${grade===2?'primary':''}">中二 · 单元一至四</button>${grade===2?`<select id="unit" aria-label="选择单元"><option value="0">All units（全部单元）</option>${[1,2,3,4].map(u=>`<option value="${u}" ${unit===u?'selected':''}>单元${u}</option>`).join('')}</select>`:''}</div><details><summary>Student details（学生资料）</summary><div class="fields">${[['name','Name（姓名）'],['class','Class（班级）'],['number','Number（学号）']].map(([k,t])=>`<label>${t}<input data-profile="${k}" value="${esc(S.profile[k])}" autocomplete="off"></label>`).join('')}</div></details><div class="lessons">${list.map(l=>{const sc=score(l);return `<a class="lesson" href="#${l.id}/learn/0"><span class="tag">单元${l.unit} · 第${l.lesson}课</span><h2 class="cn">${esc(l.title)}</h2><small>${l.words.length} words（词语） · ${sc.done}/${l.words.length} completed</small><div class="progress"><div style="width:${100*sc.done/l.words.length}%"></div></div><span>Look → Match → Use（看图 → 认词 → 运用）</span></a>`}).join('')}</div>${foot()}`;bind()}
function order(l,i,m){const k=`${l.id}:${i}:${m}`;if(!S.orders[k]){let a=[0,1,2,3];for(let j=3;j>0;j--){let k=Math.floor(Math.random()*(j+1));[a[j],a[k]]=[a[k],a[j]]}S.orders[k]=a;save()}return S.orders[k]}
function quiz(l,i,w,m){const a=recordFor(l,i,m),opts=[w.w,...w.wrong],ord=order(l,i,m),last=a.attempts.at(-1);let feedback='';if(a.done)feedback=`<div class="feedback ok"><b>${last?.ok?'Correct（答对）':'Reference（参考）'}: ${esc(w.w)}</b><p>${esc(w.zh)} · ${esc(w.en)}</p><p class="sentence">${esc(w.ex).replace('___',`<b>${esc(w.w)}</b>`)}</p>${w.note?`<p>${esc(w.note)}</p>`:''}<span class="sub">${a.attempts.length===1&&!a.help?'First try（首次）':'After support / correction（提示或订正后）'}</span></div>`;else if(last)feedback=`<div class="feedback"><b>Try again（再想想）</b><p>${a.help?esc(w.hint):'Read the whole situation. Which word fits the action or feeling?（看完整情境，留意动作或感受）'}</p></div>`;
return `<section class="card"><div class="step">${m==='picture'?'Match the picture and clue（看图认词）':'Choose the word that fits（选词填空）'}</div>${m==='picture'?`<div class="split"><div>${art(l,i)}</div><div><p class="meaning cn">${esc(w.zh)}</p><div class="options">${ord.map((k,j)=>option(opts,k,j,a)).join('')}</div></div></div>`:`<p class="sentence">${esc(w.ex).replace('___','<b>________</b>')}</p><div class="options">${ord.map((k,j)=>option(opts,k,j,a)).join('')}</div>`}<div class="bar"><button data-act="hint" ${a.done?'disabled':''}>Need help?（提示）</button><span id="lockMsg" aria-live="polite"></span></div>${a.help&&!a.done?`<div class="feedback"><p>${esc(w.zh)} · ${esc(w.en)}</p>${m==='use'?art(l,i):''}</div>`:''}<div aria-live="polite">${feedback}</div>${a.attempts.length>=2&&!a.done?'<button data-act="reveal">Explain（看解析）</button>':''}${a.done?`<div class="bar"><button class="primary" data-act="advance">${m==='picture'?'Use without picture（脱图运用）':'Continue（继续）'} →</button></div>`:''}</section>`}
function option(opts,k,j,a){return `<button class="option ${a.done&&k===0?'good':a.attempts.at(-1)?.choice===opts[k]&&!a.attempts.at(-1)?.ok?'bad':''}" data-answer="${k}" ${a.done||a.lockUntil>Date.now()?'disabled':''}>${'ABCD'[j]}. ${esc(opts[k])}</button>`}
function lockTick(){const a=recordFor(R.l,R.n,R.mode),left=Math.ceil((a.lockUntil-Date.now())/1000);if(left>0){$('#lockMsg').textContent=`Read the clue（先看提示） ${left}s`;timer=setTimeout(lockTick,300)}else{$('#lockMsg').textContent='';if(!a.done)document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=false)}}
function review(l){return `<div class="card"><h2>My progress（学习进度）</h2><p class="sub">First answers and corrections are recorded separately（首次答案与订正分开记录）.</p><div class="table-wrap"><table><thead><tr><th>Word（词语）</th><th>Look（学习）</th><th>Use（运用）</th><th>Next（下一步）</th></tr></thead><tbody>${l.words.map((w,i)=>{const a=S.answers[`${l.id}:${i}:use`];return `<tr><td class="cn">${esc(w.w)}</td><td>${S.views[`${l.id}:${i}`]?'Viewed（已看）':'—'}</td><td>${!a?.attempts.length?'Not tried（未做）':a.attempts[0].ok&&!a.attempts[0].help?'First try correct（首次独立正确）':a.done?'Reviewed（已订正/解析）':'Try again（待订正）'}</td><td><button data-retry="${i}">Practise（练习）</button></td></tr>`}).join('')}</tbody></table></div><div class="bar"><button data-act="export">Export CSV（导出）</button><button data-act="export-json">Backup（备份）</button></div></div>`}
function writing(l,i,w){return `<div class="card"><div class="step">Look → Hide → Write → Check（看 → 遮 → 写 → 核对）</div><h2 id="writeWord" class="word">${esc(w.w)}</h2><div class="bar"><button data-act="hide-word">Hide / Show（遮住／显示）</button><button data-act="speak">Listen（听词语）</button><button data-act="clear-drawing">Clear（重写）</button></div><canvas class="writing" aria-label="手写练习画布"></canvas><p class="sub">Use Apple Pencil or a finger. Check against the word above（用笔或手指写，再核对字形）. Handwriting is not automatically marked（手写不自动评分）.</p></div>`}
function initCanvas(){let c=$('canvas'),ctx=c.getContext('2d'),ratio=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*ratio;c.height=r.height*ratio;ctx.scale(ratio,ratio);ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#203744';const key=`${R.l.id}:${R.n}`;let down=false,old=S.drawings[key];if(old){let im=new Image;im.onload=()=>ctx.drawImage(im,0,0,r.width,r.height);im.src=old}c.onpointerdown=e=>{down=true;c.setPointerCapture(e.pointerId);const b=c.getBoundingClientRect();ctx.beginPath();ctx.moveTo(e.clientX-b.left,e.clientY-b.top);e.preventDefault()};c.onpointermove=e=>{if(!down)return;const b=c.getBoundingClientRect();ctx.lineTo(e.clientX-b.left,e.clientY-b.top);ctx.stroke();e.preventDefault()};const end=()=>{if(down){down=false;S.drawings[key]=c.toDataURL();save()}};c.onpointerup=end;c.onpointercancel=end;}
function speak(){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let t=new SpeechSynthesisUtterance(R.l.words[R.n].w);t.lang='zh-CN';t.rate=.8;let v=speechSynthesis.getVoices().find(v=>v.lang==='zh-CN');if(v)t.voice=v;speechSynthesis.speak(t)}
function download(text,type,name){let u=URL.createObjectURL(new Blob([text],{type}));let a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportCSV(){let rows=[['姓名','班级','学号','年级','单元','课文','词语','题型','尝试序号','答案','正确','使用提示','时间']];for(const l of D.lessons)l.words.forEach((w,i)=>['picture','use'].forEach(m=>{const a=S.answers[`${l.id}:${i}:${m}`];a?.attempts.forEach((x,j)=>rows.push([S.profile.name,S.profile.class,S.profile.number,l.grade,l.unit,l.title,w.w,m,j+1,x.choice,x.ok?'1':'0',x.help?'1':'0',x.time]))}));const quote=x=>'"'+String(x).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';download('\ufeff'+rows.map(r=>r.map(quote).join(',')).join('\r\n'),'text/csv;charset=utf-8','词语逐题记录.csv')}
function bind(){document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{grade=Number(b.dataset.grade);unit=0;home()});if($('#unit'))$('#unit').onchange=e=>{unit=Number(e.target.value);home()};document.querySelectorAll('[data-profile]').forEach(x=>x.oninput=()=>{S.profile[x.dataset.profile]=x.value;save()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>goto(R.l,b.dataset.mode,R.n));document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>goto(R.l,R.mode,Number(b.dataset.word)));document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>{let i=Number(b.dataset.retry),a=recordFor(R.l,i,'use');a.done=false;a.lockUntil=0;save();goto(R.l,'use',i)});document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{let a=recordFor(R.l,R.n,R.mode);if(a.done||a.lockUntil>Date.now())return;const w=R.l.words[R.n],k=Number(b.dataset.answer),ok=k===0;a.attempts.push({choice:[w.w,...w.wrong][k],ok,help:a.help,time:new Date().toISOString()});if(ok)a.done=true;else a.lockUntil=Date.now()+5000;save();render()});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act))}
function act(action){const {l,n,mode}=R;if(action==='home'){location.hash='';return}if(action==='export'){exportCSV();return}if(action==='export-json'){download(JSON.stringify(S,null,2),'application/json','词语学习备份.json');return}if(action==='prev'||action==='next'){goto(l,mode,n+(action==='prev'?-1:1));return}if(action==='speak'){speak();return}if(action==='hide-word'){let el=$('#writeWord');el.style.visibility=el.style.visibility==='hidden'?'visible':'hidden';return}if(action==='clear-drawing'){delete S.drawings[`${l.id}:${n}`];save();initCanvas();return}if(action==='advance'){if(mode==='picture')goto(l,'use',n);else if(n<l.words.length-1)goto(l,'use',n+1);else goto(l,'review');return}let a=recordFor(l,n,mode);if(action==='hint'){a.help=true;save();render()}if(action==='reveal'){a.help=true;a.done=true;a.revealed=true;save();render()}}
$('#record').onclick=()=>{$('#modalBody').innerHTML=`<h2>Learning record（学习记录）</h2><p>Saved on this device only（只保存在此设备）.</p><button id="csv">Export CSV（逐题记录）</button> <button id="backup">Backup JSON（备份）</button><p class="sub">The file includes student details, each answer, help use and corrections（包括资料、答案、提示与订正）.</p>`;$('#csv').onclick=exportCSV;$('#backup').onclick=()=>act('export-json');$('#modal').showModal()};$('#closeModal').onclick=()=>$('#modal').close();
fetch('data.json?v='+VERSION).then(r=>{if(!r.ok)throw Error('data');return r.json()}).then(d=>{D=d;window.addEventListener('hashchange',route);route()}).catch(()=>{$('#app').innerHTML='<p>Could not load（加载失败）. Please refresh（请刷新）.</p>'});
