const SB_URL="https://rodtizxezbtlhnuljzsc.supabase.co";
const SB_KEY="sb_publishable_NcVlurSiCAxUCQbkdQ_ZsQ_h_O1h6HU";
const TEAM_NAMES=["蓝队","红队","绿队","橙队","紫队","青队"];
let rt=null,channel=null,room="",me=null,assignedTeam="",gameCfg=null;
let teacherPlayers={},teacherWrongs={},teamN=6,started=false;
let queue=[],idx=0,uniqueDone=new Set(),initialCorrect=new Set(),mastered=new Set(),wrongOnce=new Set(),points=0,qStarted=0,current=null,locked=false;
const $=id=>document.getElementById(id);
function hideAll(){["home","teacherSetup","teacherRoom","studentJoin","studentWait","game","studentEnd"].forEach(x=>$(x).classList.add("hidden"));}
function showHome(){location.href="/";}
function openTeacher(){hideAll();$("teacherSetup").classList.remove("hidden");}
function openStudent(){hideAll();$("studentJoin").classList.remove("hidden");}
function msg(id,t,warn=false){let e=$(id);e.textContent=t;e.classList.remove("hidden");e.classList.toggle("warn",warn);}
function rid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);}
function roomCode(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join("");}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function connect(chName,onReady){if(!window.supabase)throw Error("网络组件没有载入，请刷新。");rt=window.supabase.createClient(SB_URL,SB_KEY,{realtime:{params:{eventsPerSecond:20}}});channel=rt.channel(chName,{config:{broadcast:{self:false}}});channel.subscribe(st=>{if(st==="SUBSCRIBED")onReady();});}
async function send(event,payload){if(!channel)return;try{await channel.send({type:"broadcast",event,payload});}catch(e){console.warn(e);}}

function teacherCreate(){teamN=+$("teamCount").value;room=roomCode();teacherPlayers={};teacherWrongs={};started=false;hideAll();$("teacherRoom").classList.remove("hidden");$("teacherCode").textContent=room;renderTeacher();try{connect("hwt-pk-"+room,()=>{listenTeacher();send("host_hello",{room,started:false});setInterval(()=>send("host_hello",{room,started}),3000);});}catch(e){msg("teacherState","连接失败："+e.message,true);}}
function listenTeacher(){
 channel.on("broadcast",{event:"join_request"},({payload:p})=>{if(!p?.id||!p?.name)return;if(!teacherPlayers[p.id]){let counts=Array(teamN).fill(0);Object.values(teacherPlayers).forEach(x=>{if(x.teamIndex>=0&&x.teamIndex<teamN)counts[x.teamIndex]++;});let ti=counts.indexOf(Math.min(...counts));teacherPlayers[p.id]={...p,teamIndex:ti,team:TEAM_NAMES[ti],done:0,total:0,initialCorrect:0,mastered:0,points:0,finished:false};}let x=teacherPlayers[p.id];send("assign",{target:p.id,team:x.team,teamIndex:x.teamIndex,started,config:started?gameCfg:null});renderTeacher();});
 channel.on("broadcast",{event:"progress"},({payload:p})=>{if(!p?.id||!teacherPlayers[p.id])return;Object.assign(teacherPlayers[p.id],p);if(p.wrongTerm)teacherWrongs[p.wrongTerm]=(teacherWrongs[p.wrongTerm]||0)+1;renderTeacher();broadcastScore();});
 channel.on("broadcast",{event:"finished"},({payload:p})=>{if(teacherPlayers[p?.id]){Object.assign(teacherPlayers[p.id],p,{finished:true});renderTeacher();broadcastScore();}});
}
function teacherStart(){if(started)return;const includeV=$("useVocab").checked,includeI=$("useIdiom").checked;if(!includeV&&!includeI){alert("请至少选择词语或成语。");return;}gameCfg={includeVocab:includeV,includeIdiom:includeI,total:(includeV?DATA.vocab.length:0)+(includeI?DATA.idiom.length:0),teamN};started=true;$("startBtn").disabled=true;$("startBtn").textContent="比赛进行中";send("start_game",gameCfg);$("teacherState").textContent=`比赛已开始：每人 ${gameCfg.total} 个目标词，答错词会延迟重现。`;broadcastScore();}
function calcTeams(){let arr=Array.from({length:teamN},(_,i)=>({name:TEAM_NAMES[i],players:[],acc:0,master:0,pts:0}));Object.values(teacherPlayers).forEach(p=>arr[p.teamIndex]?.players.push(p));arr.forEach(t=>{if(t.players.length){t.acc=t.players.reduce((s,p)=>s+(p.done?100*p.initialCorrect/p.done:0),0)/t.players.length;t.master=t.players.reduce((s,p)=>s+(p.total?100*p.mastered/p.total:0),0)/t.players.length;t.pts=Math.round(t.players.reduce((s,p)=>s+(p.points||0),0)/t.players.length);}});return arr;}
function broadcastScore(){let teams=calcTeams().map(t=>({name:t.name,acc:Math.round(t.acc),master:Math.round(t.master),pts:t.pts,n:t.players.length}));send("scoreboard",{teams});}
function renderTeacher(){let ps=Object.values(teacherPlayers),done=ps.reduce((s,p)=>s+(p.done||0),0),ic=ps.reduce((s,p)=>s+(p.initialCorrect||0),0),tot=ps.reduce((s,p)=>s+(p.total||0),0),mast=ps.reduce((s,p)=>s+(p.mastered||0),0);$("playerCount").textContent=ps.length;$("finishedCount").textContent=ps.filter(p=>p.finished).length;$("classAcc").textContent=done?Math.round(ic*100/done)+"%":"—";$("classMaster").textContent=tot?Math.round(mast*100/tot)+"%":"—";let teams=calcTeams();$("teamBoard").innerHTML=teams.map(t=>`<div class="team"><b>${t.name} <span class="small">(${t.players.length})</span></b><div class="bar"><i style="width:${Math.min(100,t.acc)}%"></i></div><span>${Math.round(t.acc)}% · ${t.pts}</span></div>`).join("");$("rosterBody").innerHTML=ps.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.team}</td><td>${p.done||0}/${p.total||"—"}</td><td>${p.done?Math.round((p.initialCorrect||0)*100/p.done):0}%</td><td>${p.finished?"完成":"进行中"}</td></tr>`).join("");let ws=Object.entries(teacherWrongs).sort((a,b)=>b[1]-a[1]).slice(0,12);$("wrongList").innerHTML=ws.length?ws.map(([w,n],i)=>`<span class="pill">${i+1}. ${esc(w)} · ${n}次</span>`).join(" "):"尚无数据";}

function studentJoin(){room=$("roomInput").value.trim().toUpperCase();let name=$("nameInput").value.trim(),cl=$("classInput").value.trim(),no=$("noInput").value.trim();if(!/^[A-Z2-9]{6}$/.test(room)||!name||!cl||!no){msg("joinMsg","请填写完整资料和6位房间码。",true);return;}me={id:localStorage.getItem("hwtPkId")||rid(),name,className:cl,studentNo:no};localStorage.setItem("hwtPkId",me.id);hideAll();$("studentWait").classList.remove("hidden");$("studentCode").textContent=room;try{connect("hwt-pk-"+room,()=>{listenStudent();send("join_request",me);setInterval(()=>{if(!started)send("join_request",me)},2500);});}catch(e){alert(e.message);}}
function listenStudent(){channel.on("broadcast",{event:"host_hello"},()=>send("join_request",me));channel.on("broadcast",{event:"assign"},({payload:p})=>{if(p?.target!==me.id)return;assignedTeam=p.team;$("studentTeam").textContent=assignedTeam;if(p.started&&p.config&&!started)beginGame(p.config);});channel.on("broadcast",{event:"start_game"},({payload:p})=>{if(!started)beginGame(p);});channel.on("broadcast",{event:"scoreboard"},({payload:p})=>{let t=p?.teams?.find(x=>x.name===assignedTeam);if(t&&$("teamLabel"))$("teamLabel").textContent=`${assignedTeam}｜团队初次正确率 ${t.acc}%`;});}
function allTargets(cfg){return [...(cfg.includeVocab?DATA.vocab:[]),...(cfg.includeIdiom?DATA.idiom:[])];}
function makeQuestions(cfg){return shuffle(allTargets(cfg).map(t=>({...t,qid:t.kind+"-"+t.term,repeat:false})));}
function beginGame(cfg){started=true;gameCfg=cfg;queue=makeQuestions(cfg);idx=0;uniqueDone=new Set();initialCorrect=new Set();mastered=new Set();wrongOnce=new Set();points=0;hideAll();$("game").classList.remove("hidden");$("teamLabel").textContent=assignedTeam;renderQuestion();}
function distractorsFor(t,mode){let pool=DATA[t.kind==="idiom"?"idiom":"vocab"].filter(x=>x.term!==t.term);if(mode==="meaning")return shuffle(pool).slice(0,3).map(x=>x.zh);return shuffle(pool).slice(0,3).map(x=>x.term);}
function renderQuestion(){if(idx>=queue.length){finishGame();return;}current=queue[idx];locked=false;qStarted=performance.now();let mode=current.context?"context":"meaning",opts,answer;if(mode==="context"){answer=current.term;opts=shuffle([answer,...distractorsFor(current,"context")]);$("qType").textContent=current.repeat?"错词复活 · 选择最合适的词语／成语":"语境题 · 选择最合适的词语／成语";$("qText").textContent=current.context.replace(/_+/g,"______");}else{answer=current.zh;opts=shuffle([answer,...distractorsFor(current,"meaning")]);$("qType").textContent=current.repeat?"错词复活 · 选择正确意思":"词义题 · 选择最恰当的意思";$("qText").textContent=current.term;}current._answer=answer;current._opts=opts;$("options").innerHTML=opts.map((o,i)=>`<button class="opt" onclick="answer(${i})">${esc(o)}</button>`).join("");$("feedback").className="feedback hidden";$("nextBtn").classList.add("hidden");let uniq=uniqueDone.size,total=gameCfg.total;$("qCount").textContent=`已完成 ${uniq} / ${total}`;$("pbar").style.width=Math.min(100,uniq*100/total)+"%";}
function answer(i){if(locked)return;locked=true;const opts=[...document.querySelectorAll(".opt")],chosen=current._opts[i],ok=chosen===current._answer;opts.forEach((b,j)=>{if(current._opts[j]===current._answer)b.classList.add("correct");else if(j===i)b.classList.add("wrong");b.disabled=true;});let first=!uniqueDone.has(current.qid);if(first){uniqueDone.add(current.qid);if(ok){initialCorrect.add(current.qid);mastered.add(current.qid);}else{wrongOnce.add(current.qid);let pos=Math.min(queue.length,idx+6+Math.floor(Math.random()*3));queue.splice(pos,0,{...current,repeat:true});}}else if(ok)mastered.add(current.qid);let elapsed=(performance.now()-qStarted)/1000;if(ok)points+=current.repeat?60:100+Math.max(0,Math.round(10-Math.min(10,elapsed/1.2)));const fb=$("feedback");fb.className="feedback "+(ok?"ok":"bad");let prefix=ok?(current.repeat?"🔥 成功记住！":"✅ 正确"):"❌ 再记一记";let use=current.kind==="idiom"?(current.context?current.context.replace(/_+/g,current.term):""):(current.coll||"");fb.innerHTML=`<strong>${prefix}</strong><div class="term">${esc(current.term)} = ${esc(current.en)}</div><div>${esc(current.zh)}</div>${use?`<div><b>${current.kind==="idiom"?"例句":"常见搭配"}：</b>${esc(use)}</div>`:""}`;$("nextBtn").classList.remove("hidden");send("progress",{id:me.id,name:me.name,team:assignedTeam,done:uniqueDone.size,total:gameCfg.total,initialCorrect:initialCorrect.size,mastered:mastered.size,points,wrongTerm:(!ok&&first)?current.term:null,finished:false});}
function nextQuestion(){idx++;renderQuestion();}
function finishGame(){hideAll();$("studentEnd").classList.remove("hidden");let total=gameCfg.total;$("endAcc").textContent=Math.round(initialCorrect.size*100/total)+"%";$("endMaster").textContent=Math.round(mastered.size*100/total)+"%";$("endPoints").textContent=points;$("endWrong").textContent=wrongOnce.size;send("finished",{id:me.id,name:me.name,team:assignedTeam,done:total,total,initialCorrect:initialCorrect.size,mastered:mastered.size,points,finished:true});}